import { notFound, redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { FormField, FormPageLayout, FormSection, PageHeader, PrimaryButton, SecondaryButton } from "@/components/ui";
import { logActivity } from "@/lib/activity-log";
import { getCurrentProfile } from "@/lib/auth";
import { getSupabaseServerClient } from "@/lib/supabase-server";

async function updateMachine(fd: FormData) {"use server"; const s=getSupabaseServerClient(); if(!s) return; const profile = await getCurrentProfile(); const id=String(fd.get("id")); const { data: beforeMachine } = await s.from("machines").select("*").eq("id", id).maybeSingle(); const payload={machine_code:String(fd.get("machine_code")||"").trim(),vms_machine_id:String(fd.get("vms_machine_id")||"")||null,name:String(fd.get("name")||"").trim(),machine_type:String(fd.get("machine_type")||"lift"),location_id:String(fd.get("location_id")||"")||null,rent_amount:Number(fd.get("rent_amount")||0),status:String(fd.get("status")||"active"),target_nsm:Number(fd.get("target_nsm")||0),target_uptime_percent:Number(fd.get("target_uptime_percent")||98)}; const { data: afterMachine } = await s.from("machines").update(payload).eq("id",id).select("*").maybeSingle(); await logActivity({ profile, action: "update", entityType: "machine", entityId: id, entityLabel: afterMachine?.name ?? payload.name, beforeData: beforeMachine, afterData: afterMachine ?? payload, summary: `Updated machine ${afterMachine?.name ?? payload.name}` }); revalidatePath("/machines"); redirect("/machines"); }

export default async function EditMachinePage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const s=getSupabaseServerClient(); if(!s) notFound(); const [{data:machine},{data:locations}] = await Promise.all([s.from("machines").select("*").eq("id",id).single(), s.from("locations").select("id,name").order("name")]); if(!machine) notFound();
return <><FormPageLayout><PageHeader title="Edit machine" subtitle="Update machine profile and targets." breadcrumbs={[{ label: "Machines", href: "/machines" }, { label: machine.name ?? id.slice(0, 8) }, { label: "Edit machine" }]}/><form action={updateMachine} className="space-y-5"><input type="hidden" name="id" value={id}/><FormSection title="Machine details"><div className="grid gap-4 md:grid-cols-2">
<FormField label="Internal Machine Code" required><input required name="machine_code" defaultValue={machine.machine_code} className="field-input"/></FormField><FormField label="VMS Machine ID"><input name="vms_machine_id" defaultValue={machine.vms_machine_id||""} className="field-input"/></FormField><FormField label="Machine Name" required><input required name="name" defaultValue={machine.name} className="field-input"/></FormField><FormField label="Machine Type" required><select name="machine_type" defaultValue={machine.machine_type} className="field-input"><option>lift</option><option>non-lift</option><option>coffee</option><option>other</option></select></FormField><FormField label="Location"><select name="location_id" defaultValue={machine.location_id||""} className="field-input"><option value="">Select location</option>{locations?.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></FormField><FormField label="Status" required><select name="status" defaultValue={machine.status} className="field-input"><option>active</option><option>inactive</option><option>maintenance</option><option>incoming</option><option>relocated</option></select></FormField></div></FormSection><div className="flex gap-3"><PrimaryButton>Save changes</PrimaryButton><SecondaryButton href="/machines">Cancel</SecondaryButton></div></form></FormPageLayout></>; }
