import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {redirect} from 'next/navigation';
import {getCurrentProfile,getAuthenticatedSupabaseServerClient} from '@/lib/auth';
import {hasAnyRole,isOwnerAdminRole} from '@/lib/authz';
import {getServerI18n} from '@/lib/i18n/server';
import {PageHeader,ErrorState} from '@/components/ui';
import {CrmRoutineEditor,CrmRoutineAction} from '@/components/CrmRoutineEditor';
import {crmRecurringEnabled,routineId,routineEngineId,type RoutineData} from '@/lib/crm-recurring';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const profile=await getCurrentProfile();if(!profile||profile.active_status!=='active'||!hasAnyRole(profile,['owner','admin','supervisor']))redirect('/unauthorized');
 const {locale}=await getServerI18n(),ar=locale==='ar',tr=(en:string,a:string)=>ar?a:en;
 if(!crmRecurringEnabled)return <ErrorState title={tr('Recurring work is not enabled','العمل الدوري غير مفعّل')} body={tr('Existing work is unchanged. Enable only after the matching database rollout.','لم يتغير العمل الحالي. يُفعّل القسم بعد نشر تحديث قاعدة البيانات المطابق.')}/>;
 const p=await searchParams;const get=(k:string)=>typeof p[k]==='string'?String(p[k]):'';
 if(get('new')==='1'&&!routineId.test(get('id')))redirect(`/my-work/team/routines?new=1&id=${randomUUID()}`);
 const filters={q:get('q'),state:get('state'),offset:get('offset')||'0'};let data:RoutineData;
 try{const db=await getAuthenticatedSupabaseServerClient();const result=await db?.rpc('snacky_crm_routines_v1',{p_filters:filters});if(result?.error||!result?.data)throw Error('unavailable');data=result.data as RoutineData;}
 catch{return <ErrorState title={tr('Recurring work unavailable','العمل الدوري غير متاح')} body={tr('Could not verify the schedule data. This is not an empty list. Existing tasks remain in My Work.','تعذر التحقق من الجداول. هذا لا يعني أن القائمة فارغة. تبقى المهام الحالية في عملي اليوم.')}/>;}
 const edit=data.rows.find(r=>r.id===get('edit'));const adding=get('new')==='1';
 return <div className="min-w-0 space-y-5" dir={ar?'rtl':'ltr'}>
  <PageHeader title={tr('Recurring responsibilities','المسؤوليات الدورية')} subtitle={tr('Configure once. Follow up through the existing task records.','اضبط المسؤولية مرة واحدة، وتابع التنفيذ في سجلات المهام الحالية.')} action={<Link className="btn-secondary" href="/my-work/team">{tr('Management overview','ملخص الإدارة')}</Link>}/>
  <section className="surface-card space-y-3"><h2 className="font-semibold">{data.engine.enabled?tr('Generation enabled','إنشاء المهام مفعّل'):tr('Generation paused','إنشاء المهام متوقف')}</h2><p className="text-sm">{data.scheduled?tr('Automatic scheduler configured.','تم إعداد الجدولة التلقائية.'):tr('Automatic scheduler is not configured. Activating a routine alone will not generate tasks.','الجدولة التلقائية غير معدة. تفعيل المسؤولية وحده لا ينشئ مهام.')}</p><p className="text-xs text-slate-600">{tr('Last successful run','آخر تشغيل ناجح')}: {data.engine.last_success_at?new Intl.DateTimeFormat(ar?'ar-LY':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Tripoli'}).format(new Date(data.engine.last_success_at)):tr('Not yet verified','لم يُتحقق بعد')}{data.engine.last_result?` · ${tr('Errors','أخطاء')}: ${data.engine.last_result.errors}`:''}</p>{isOwnerAdminRole(profile)?<CrmRoutineAction key={String(data.engine.enabled)} userId={profile.id} id={routineEngineId} revision={0} action={data.engine.enabled?'engine.pause':'engine.resume'} ar={ar} label={data.engine.enabled?tr('Pause all generation','إيقاف إنشاء المهام'):tr('Enable generation','تفعيل إنشاء المهام')}/>:null}</section>
  {adding||edit?<section className="surface-card space-y-4"><Link className="text-sm underline" href="/my-work/team/routines">{tr('Back to routines','العودة للمسؤوليات')}</Link><CrmRoutineEditor key={`${edit?.id??get('id')}:${edit?.revision??0}`} initial={edit} id={edit?.id??get('id')} data={data} userId={profile.id} ar={ar}/></section>:<>
   <div className="flex flex-wrap justify-between gap-3"><Link className="btn-primary" href="/my-work/team/routines?new=1">+ {tr('Add responsibility','إضافة مسؤولية')}</Link><span className="text-sm">{data.total} {tr('routines','مسؤولية')}</span></div>
   <form className="surface-card flex flex-wrap items-end gap-3" method="get"><label className="min-w-0 flex-1 text-sm">{tr('Find responsibility','البحث عن مسؤولية')}<input name="q" className="field-input mt-1" defaultValue={filters.q}/></label><label className="text-sm">{tr('Status','الحالة')}<select name="state" className="field-input mt-1" defaultValue={filters.state}><option value="">{tr('All','الكل')}</option><option value="active">{tr('Active','مفعّل')}</option><option value="paused">{tr('Paused','متوقف')}</option></select></label><button className="btn-secondary">{tr('Search','بحث')}</button></form>
   {data.rows.map(r=><article className="surface-card space-y-3" key={r.id}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{r.title}</h2><span className="text-sm">{r.paused?tr('Paused','متوقف'):r.end_on&&r.next_due_on>r.end_on?tr('Schedule ended','انتهى الجدول'):tr('Active','مفعّل')}</span></div><p className="text-sm text-slate-600">{r.assigned_name} · {r.target_title??tr('General responsibility','مسؤولية عامة')}</p><p className="text-sm">{tr('Next cycle','الدورة القادمة')}: {r.next_due_on} · {tr('Every','كل')} {r.every} {tr(r.cadence,r.cadence==='days'?'أيام':r.cadence==='weeks'?'أسابيع':'أشهر')}</p>{r.blocked_reason?<p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">{r.blocked_reason==='unfinished_followup'?tr('An unfinished follow-up is still open. No duplicate will be created.','توجد متابعة غير مكتملة. لن تُنشأ متابعة مكررة.'):tr('Needs review: source, assignee or generation failed. Existing tasks were not deleted.','تحتاج مراجعة: السجل أو المسؤول غير متاح أو فشل الإنشاء. لم تُحذف المهام الحالية.')}</p>:null}<div className="flex flex-wrap gap-2"><Link className="btn-secondary" href={`/my-work/team/routines?${new URLSearchParams({...filters,edit:r.id})}`}>{tr('Edit future work','تعديل العمل القادم')}</Link><CrmRoutineAction key={`${r.id}:${r.revision}`} userId={profile.id} id={r.id} action={r.paused?'resume':'pause'} revision={r.revision} label={r.paused?tr('Activate','تفعيل'):tr('Pause','إيقاف')} ar={ar}/></div>{r.recent_work?.length?<details><summary className="cursor-pointer text-sm font-medium">{tr('Recent generated work','آخر مهام أُنشئت')}</summary>{r.recent_work.map(o=><Link className="mt-2 block border-t py-2 text-sm underline" key={o.task_id} href={`/follow-ups/${o.task_id}`}>{o.due_on} · {o.archived_at?tr('Archived','مؤرشف'):o.status==='completed'?tr('Completed','مكتمل'):tr('Open','مفتوح')} · {o.assigned_name}{o.skipped_cycles?` · ${o.skipped_cycles} ${tr('missed cycles combined','دورات فائتة دُمجت')}`:''}</Link>)}</details>:null}</article>)}
   {!data.rows.length?<p className="surface-card text-sm">{tr('No matching routines. Add one with a real owner and a first due date.','لا توجد مسؤوليات مطابقة. أضف مسؤولية مع موظف محدد وأول موعد استحقاق.')}</p>:null}
   <div className="flex gap-3">{data.offset>0?<Link className="btn-secondary" href={`?${new URLSearchParams({...filters,offset:String(Math.max(0,data.offset-20))})}`}>{tr('Previous','السابق')}</Link>:null}{data.offset+20<data.total?<Link className="btn-secondary" href={`?${new URLSearchParams({...filters,offset:String(data.offset+20)})}`}>{tr('Next','التالي')}</Link>:null}</div>
  </>}
 </div>;
}
