"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Row = Record<string, any>;
type Snapshot = { manager:boolean; currentPersonId:string|null; selectedPersonId:string|null; team:Row[]; products:Row[]; balances:Row[]; purchases:Row[]; payments:Row[]; advances:Row[]; expenses:Row[]; returns:Row[] };
type Props = { initialPersonId?:string; lockPerson?:boolean; locale?:string; selfServiceOnly?:boolean };
type Tab = "overview"|"purchase"|"expense"|"history";

const money=(v:unknown)=>`${Number(v??0).toFixed(2)} LYD`;
const nowLocal=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
function browserLocale(fallback:string){
 if(typeof window==="undefined")return fallback;
 const saved=window.localStorage.getItem("snacky_os_language");
 const cookie=document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("snacky_os_language="))?.split("=")[1];
 const html=document.documentElement.lang;
 return [saved,cookie,html,fallback].find(x=>x==="ar"||x==="en")||"ar";
}

export default function OperatorMoneyLedgerClient({initialPersonId="",lockPerson=false,locale="ar",selfServiceOnly=false}:Props){
 const [activeLocale,setActiveLocale]=useState(locale);
 const ar=activeLocale==="ar";
 const tx=(en:string,arabic:string)=>ar?arabic:en;
 const [data,setData]=useState<Snapshot|null>(null),[personId,setPersonId]=useState(initialPersonId),[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[message,setMessage]=useState(""),[tab,setTab]=useState<Tab>("overview");
 useEffect(()=>{
  const sync=()=>setActiveLocale(browserLocale(locale));
  sync();
  window.addEventListener("storage",sync);
  window.addEventListener("focus",sync);
  const observer=new MutationObserver(sync);
  observer.observe(document.documentElement,{attributes:true,attributeFilter:["lang","dir"]});
  return()=>{window.removeEventListener("storage",sync);window.removeEventListener("focus",sync);observer.disconnect()};
 },[locale]);
 const load=useCallback(async(id?:string)=>{setLoading(true);const target=id||initialPersonId;const r=await fetch(`/api/operator-money${target?`?personId=${target}`:""}`,{cache:"no-store"});const j=await r.json();setLoading(false);if(!r.ok){setData(null);setMessage(j.error||tx("Could not load money records","تعذر تحميل السجل المالي"));return;}setData(j);setPersonId(j.selectedPersonId||target||j.currentPersonId||j.team?.[0]?.id||"");},[initialPersonId,ar]);
 useEffect(()=>{void load(initialPersonId)},[initialPersonId,load]);
 const post=async(action:string,body:Row)=>{setSaving(action);setMessage("");const r=await fetch("/api/operator-money",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,personId,...body,clientSubmissionId:body.clientSubmissionId||`${action}:${crypto.randomUUID()}`})});const j=await r.json();setSaving("");if(!r.ok){setMessage(j.error||tx("Save failed","فشل الحفظ"));return false;}setMessage(action==="purchase"?tx("Purchase recorded successfully.","تم تسجيل المشتريات بنجاح."):tx("Expense submitted for review.","تم إرسال المصروف للمراجعة."));await load(personId);return true};
 const balance=useMemo(()=>data?.balances.find(x=>x.person_id===personId),[data,personId]);
 if(loading&&!data)return <div dir={ar?"rtl":"ltr"} className="surface-card p-6">{tx("Loading…","جارٍ التحميل…")}</div>;
 if(!data)return <div dir={ar?"rtl":"ltr"} className="surface-card border-red-200 p-6 text-red-700">{message||tx("Money records are unavailable.","السجل المالي غير متاح.")}</div>;
 const self=!data.manager||selfServiceOnly;
 const tabs=self?[["overview",tx("Overview","نظرة عامة")],["purchase",tx("Buy from storage","شراء من المخزن")],["expense",tx("Submit expense","تسجيل مصروف")],["history",tx("History","السجل")]]:[["overview",tx("Overview","نظرة عامة")],["history",tx("History & review","السجل والمراجعة")]];
 return <div id="my-money" dir={ar?"rtl":"ltr"} className="space-y-5">
  <div className="rounded-2xl bg-slate-900 p-5 text-white"><h1 className="text-2xl font-bold">{tx("My Money","أموالي")}</h1><p className="mt-1 text-sm text-slate-300">{tx("Record personal products and submit Snacky work expenses.","سجّل المنتجات الشخصية ومصروفات العمل الخاصة بسناكي.")}</p></div>
  {data.manager&&!lockPerson&&!selfServiceOnly?<div className="surface-card p-4"><label className="text-sm font-semibold">{tx("Operator","المشغّل")}</label><select className="input mt-2" value={personId} onChange={e=>{setPersonId(e.target.value);void load(e.target.value)}}>{data.team.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></div>:null}
  <div className="rounded-2xl border border-slate-200 bg-white p-1 shadow-sm"><div className="flex gap-1 overflow-x-auto">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id as Tab)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===id?"bg-slate-900 text-white":"text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</div></div>
  {message?<div className="rounded-xl border border-slate-200 bg-white p-3 text-sm">{message}</div>:null}
  {tab==="overview"?<Overview ar={ar} balance={balance} self={self} onTab={setTab} data={data} personId={personId} post={post}/>:null}
  {tab==="purchase"&&self?<PurchasePanel ar={ar} products={data.products} saving={saving==="purchase"} onPost={post}/>:null}
  {tab==="expense"&&self?<ExpensePanel ar={ar} advances={data.advances.filter(x=>x.person_id===personId)} saving={saving==="expense"} onPost={post}/>:null}
  {tab==="history"?<History ar={ar} data={data} personId={personId} manager={data.manager&&!selfServiceOnly} post={post}/>:null}
 </div>
}

function Overview({ar,balance,self,onTab,data,personId,post}:{ar:boolean;balance?:Row;self:boolean;onTab:(t:Tab)=>void;data:Snapshot;personId:string;post:(a:string,b:Row)=>Promise<boolean>}){const t=(e:string,a:string)=>ar?a:e;return <div className="space-y-5">
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[[t("Personal debt","الدين الشخصي"),balance?.personal_debt_remaining_lyd],[t("Work money received","أموال العمل المستلمة"),balance?.advanced_lyd],[t("Approved expenses","المصروفات المعتمدة"),balance?.approved_expenses_lyd],[t("Money returned","الأموال المرجعة"),balance?.returned_money_lyd],[t("Still to account for","المبلغ المطلوب تسويته"),balance?.unaccounted_advance_lyd]].map(([l,v])=><div className="surface-card p-4" key={String(l)}><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{money(v)}</div></div>)}</div>
 {self?<div className="grid gap-4 md:grid-cols-2"><button onClick={()=>onTab("purchase")} className="rounded-2xl border border-slate-200 bg-white p-5 text-start shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="text-lg font-bold">{t("I took products for myself","أخذت منتجات للاستخدام الشخصي")}</div><p className="mt-2 text-sm text-slate-500">{t("Search, select quantity, and confirm. Storage is chosen automatically.","ابحث عن المنتج وحدد الكمية وأكد. يتم اختيار المخزن تلقائياً.")}</p></button><button onClick={()=>onTab("expense")} className="rounded-2xl border border-slate-200 bg-white p-5 text-start shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="text-lg font-bold">{t("I paid for Snacky work","دفعت مصروفاً خاصاً بسناكي")}</div><p className="mt-2 text-sm text-slate-500">{t("Submit fuel, maintenance, supplies, or delivery costs.","سجّل الوقود أو الصيانة أو المستلزمات أو التوصيل.")}</p></button></div>:<ManagerActions ar={ar} data={data} personId={personId} post={post}/>}<Recent ar={ar} data={data} personId={personId}/></div>}

function PurchasePanel({ar,products,saving,onPost}:{ar:boolean;products:Row[];saving:boolean;onPost:(a:string,b:Row)=>Promise<boolean>}){const t=(e:string,a:string)=>ar?a:e;const [q,setQ]=useState(""),[cat,setCat]=useState("all"),[pid,setPid]=useState(""),[price,setPrice]=useState(0),[qty,setQty]=useState(1),[source,setSource]=useState<Row|null>(null),[checking,setChecking]=useState(false);const cats=useMemo(()=>["all",...Array.from(new Set(products.map(x=>String(x.category||"Other"))))],[products]);const filtered=useMemo(()=>products.filter(x=>(cat==="all"||String(x.category||"Other")===cat)&&`${x.name||""} ${x.brand||""} ${x.category||""}`.toLowerCase().includes(q.toLowerCase())).slice(0,15),[products,q,cat]);const selected=products.find(x=>x.id===pid);
 const choose=async(p:Row)=>{setPid(p.id);setPrice(Number(p.current_selling_price_lyd??p.selling_price??0));setSource(null);setChecking(true);const r=await fetch("/api/operator-money",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"availability",productId:p.id})});const j=await r.json();setChecking(false);const best=(r.ok?j.data??[]:[]).filter((x:Row)=>Number(x.available_qty)>0).sort((a:Row,b:Row)=>Number(b.available_qty)-Number(a.available_qty))[0]||null;setSource(best)};
 return <section className="surface-card p-5"><div className="max-w-3xl"><h2 className="text-xl font-bold">{t("Buy products from storage","شراء منتجات من المخزن")}</h2><p className="mt-1 text-sm text-slate-500">{t("For personal use only. Route stock is recorded during the route.","للاستخدام الشخصي فقط. منتجات المسار تُسجّل داخل المسار.")}</p><input className="input mt-5" value={q} onChange={e=>setQ(e.target.value)} placeholder={t("Search product or brand…","ابحث عن المنتج أو العلامة…")}/><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold ${cat===c?"bg-slate-900 text-white":"bg-slate-100 text-slate-600"}`}>{c==="all"?t("All","الكل"):c}</button>)}</div><div className="mt-3 max-h-80 overflow-y-auto rounded-xl border">{filtered.map(p=><button key={p.id} onClick={()=>void choose(p)} className={`flex w-full items-center justify-between border-b p-3 text-start last:border-0 ${pid===p.id?"bg-slate-100":"hover:bg-slate-50"}`}><div><div className="font-semibold">{p.name}</div><div className="text-xs text-slate-500">{[p.brand,p.category].filter(Boolean).join(" · ")}</div></div><strong>{money(p.current_selling_price_lyd??p.selling_price)}</strong></button>)}</div>
 {selected?<form className="mt-5 space-y-4 rounded-2xl bg-slate-50 p-4" onSubmit={e=>{e.preventDefault();if(!source)return;const body=Object.fromEntries(new FormData(e.currentTarget).entries());void onPost("purchase",body).then(ok=>{if(ok){setPid("");setQ("");setQty(1);setSource(null)}})}}><input type="hidden" name="productId" value={pid}/><input type="hidden" name="storageLocationId" value={source?.storage_location_id||""}/><div><div className="text-xs text-slate-500">{t("Selected product","المنتج المختار")}</div><div className="font-bold">{selected.name}</div></div>{checking?<div className="rounded-xl bg-white p-3 text-sm">{t("Checking available stock…","جارٍ التحقق من الكمية المتاحة…")}</div>:source?<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{t(`${source.available_qty} units available`,`الكمية المتاحة: ${source.available_qty}`)}</div>:<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{t("Not available in storage","المنتج غير متوفر في المخزن")}</div>}<div className="grid gap-3 sm:grid-cols-2"><div><label className="text-sm font-semibold">{t("Quantity","الكمية")}</label><input className="input mt-2" name="quantity" type="number" min="1" max={source?.available_qty||1} value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))} required/></div><div><label className="text-sm font-semibold">{t("Selling price","سعر البيع")}</label><input className="input mt-2" name="unitPrice" value={price} readOnly/></div></div><div className="flex justify-between rounded-xl bg-white p-3"><span>{t("Total debt added","الإجمالي المضاف للدين")}</span><strong>{money(qty*price)}</strong></div><textarea className="input" name="note" placeholder={t("Optional note","ملاحظة اختيارية")}/><button className="btn-primary w-full" disabled={saving||checking||!source}>{saving?t("Recording…","جارٍ التسجيل…"):t("Confirm purchase","تأكيد الشراء")}</button></form>:null}</div></section>}

function ExpensePanel({ar,advances,saving,onPost}:{ar:boolean;advances:Row[];saving:boolean;onPost:(a:string,b:Row)=>Promise<boolean>}){const t=(e:string,a:string)=>ar?a:e;return <section className="surface-card p-5"><div className="max-w-2xl"><h2 className="text-xl font-bold">{t("Submit a work expense","تسجيل مصروف عمل")}</h2><p className="mt-1 text-sm text-slate-500">{t("Admin reviews it before approval.","تتم مراجعته من الإدارة قبل الاعتماد.")}</p><form className="mt-5 grid gap-4" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;void onPost("expense",Object.fromEntries(new FormData(f).entries())).then(ok=>{if(ok)f.reset()})}}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{t("Amount","المبلغ")}<MoneyInput ar={ar}/></label><label className="text-sm font-semibold">{t("Date and time","التاريخ والوقت")}<input className="input mt-2" name="date" type="datetime-local" defaultValue={nowLocal()} required/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{t("Expense type","نوع المصروف")}<select className="input mt-2" name="expenseType" required defaultValue=""><option value="" disabled>{t("Choose type","اختر النوع")}</option><option value="Fuel">{t("Fuel","وقود")}</option><option value="Vehicle">{t("Vehicle","سيارة")}</option><option value="Machine supplies">{t("Machine supplies","مستلزمات ماكينة")}</option><option value="Storage supplies">{t("Storage supplies","مستلزمات مخزن")}</option><option value="Delivery">{t("Delivery","توصيل")}</option><option value="Other">{t("Other","أخرى")}</option></select></label><label className="text-sm font-semibold">{t("Paid to","دُفع إلى")}<input className="input mt-2" name="supplierPayee" required placeholder={t("Shop, supplier, or person","المحل أو المورد أو الشخص")}/></label></div><label className="text-sm font-semibold">{t("Related advance","العهدة المرتبطة")}<select className="input mt-2" name="advanceId"><option value="">{t("No related advance","بدون عهدة مرتبطة")}</option>{advances.map(x=><option key={x.id} value={x.id}>{x.purpose} — {money(x.amount_lyd)}</option>)}</select></label><label className="text-sm font-semibold">{t("Details","التفاصيل")}<textarea className="input mt-2" name="note" required placeholder={t("Explain the expense clearly","وضح المصروف بشكل واضح")}/></label><input className="input" name="receiptUrl" placeholder={t("Receipt link (optional)","رابط الإيصال (اختياري)")}/><button className="btn-primary w-full" disabled={saving}>{saving?t("Submitting…","جارٍ الإرسال…"):t("Submit for review","إرسال للمراجعة")}</button></form></div></section>}

function ManagerActions({ar,data,personId,post}:{ar:boolean;data:Snapshot;personId:string;post:(a:string,b:Row)=>Promise<boolean>}){const t=(e:string,a:string)=>ar?a:e;const submit=(a:string)=>(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;void post(a,Object.fromEntries(new FormData(f).entries())).then(ok=>{if(ok)f.reset()})};return <div className="grid gap-4 xl:grid-cols-3"><section className="surface-card p-4"><h3 className="font-bold">{t("Give work money","تسليم عهدة مالية")}</h3><form className="mt-3 space-y-2" onSubmit={submit("advance")}><MoneyInput ar={ar}/><input className="input" name="purpose" required placeholder={t("Purpose","الغرض")}/><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><button className="btn-primary">{t("Record advance","تسجيل العهدة")}</button></form></section><section className="surface-card p-4"><h3 className="font-bold">{t("Record debt payment","تسجيل سداد دين")}</h3><form className="mt-3 space-y-2" onSubmit={submit("debtPayment")}><MoneyInput ar={ar}/><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><input className="input" name="paymentMethod" required placeholder={t("Payment method","طريقة الدفع")}/><button className="btn-primary">{t("Record payment","تسجيل السداد")}</button></form></section><section className="surface-card p-4"><h3 className="font-bold">{t("Record returned money","تسجيل أموال مرجعة")}</h3><form className="mt-3 space-y-2" onSubmit={submit("advanceReturn")}><MoneyInput ar={ar}/><select className="input" name="advanceId"><option value="">{t("General return","إرجاع عام")}</option>{data.advances.filter(x=>x.person_id===personId).map(x=><option key={x.id} value={x.id}>{x.purpose}</option>)}</select><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><input className="input" name="paymentMethod" required placeholder={t("Method","الطريقة")}/><button className="btn-primary">{t("Record return","تسجيل الإرجاع")}</button></form></section></div>}

function Recent({ar,data,personId}:{ar:boolean;data:Snapshot;personId:string}){const t=(e:string,a:string)=>ar?a:e;const rows=[...data.purchases.filter(x=>x.person_id===personId).map(x=>({id:`p-${x.id}`,label:`${t("Personal purchase","شراء شخصي")}: ${x.product?.name??t("Product","منتج")} × ${x.quantity}`,amount:x.total_lyd,date:x.purchased_at})),...data.expenses.filter(x=>x.person_id===personId).map(x=>({id:`e-${x.id}`,label:`${t("Work expense","مصروف عمل")}: ${x.expense_type}`,amount:x.amount_lyd,date:x.spent_at}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5);return <section className="surface-card p-4"><h3 className="font-bold">{t("Recent activity","آخر الحركات")}</h3>{rows.length?<div className="mt-3 divide-y">{rows.map(x=><div key={x.id} className="flex justify-between gap-3 py-3"><div><div className="text-sm font-medium">{x.label}</div><div className="text-xs text-slate-500">{new Date(x.date).toLocaleString(ar?"ar-LY":"en-US")}</div></div><strong>{money(x.amount)}</strong></div>)}</div>:<p className="mt-3 text-sm text-slate-500">{t("No records yet.","لا توجد حركات مسجلة بعد.")}</p>}</section>}

function MoneyInput({ar}:{ar:boolean}){return <input className="input mt-2" name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ بالدينار":"Amount (LYD)"}/>}
function History({ar,data,personId,manager,post}:{ar:boolean;data:Snapshot;personId:string;manager:boolean;post:(a:string,b:Row)=>Promise<boolean>}){const t=(e:string,a:string)=>ar?a:e;const purchases=data.purchases.filter(x=>x.person_id===personId),expenses=data.expenses.filter(x=>x.person_id===personId);return <section className="surface-card p-4"><h2 className="text-xl font-bold">{t("Money history","السجل المالي")}</h2><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-start text-slate-500"><th className="p-2">{t("Type","النوع")}</th><th className="p-2">{t("Details","التفاصيل")}</th><th className="p-2">{t("Amount","المبلغ")}</th><th className="p-2">{t("Status / date","الحالة / التاريخ")}</th><th className="p-2">{t("Action","الإجراء")}</th></tr></thead><tbody>{purchases.map(x=><tr key={x.id} className="border-b"><td className="p-2">{t("Personal purchase","شراء شخصي")}</td><td className="p-2">{x.product?.name} × {x.quantity}</td><td className="p-2">{money(x.total_lyd)}</td><td className="p-2">{new Date(x.purchased_at).toLocaleString(ar?"ar-LY":"en-US")}</td><td/></tr>)}{expenses.map(x=><tr key={x.id} className="border-b"><td className="p-2">{t("Work expense","مصروف عمل")}</td><td className="p-2">{x.expense_type} — {x.supplier_payee}</td><td className="p-2">{money(x.amount_lyd)}</td><td className="p-2">{x.status}</td><td className="p-2">{manager&&x.status==="submitted"?<div className="flex gap-2"><button className="btn-secondary" onClick={()=>void post("reviewExpense",{expenseId:x.id,status:"approved"})}>{t("Approve","اعتماد")}</button><button className="btn-secondary" onClick={()=>void post("reviewExpense",{expenseId:x.id,status:"rejected"})}>{t("Reject","رفض")}</button></div>:null}</td></tr>)}</tbody></table></div></section>}
