"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Row = Record<string, any>;
type Snapshot = { manager:boolean; currentPersonId:string|null; selectedPersonId:string|null; team:Row[]; products:Row[]; balances:Row[]; purchases:Row[]; payments:Row[]; advances:Row[]; expenses:Row[]; returns:Row[] };
type Props = { initialPersonId?: string; lockPerson?: boolean };
const money=(v:unknown)=>`${Number(v??0).toFixed(2)} LYD`;
const nowLocal=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);

export default function OperatorMoneyLedgerClient({initialPersonId="",lockPerson=false}:Props){
 const [data,setData]=useState<Snapshot|null>(null); const [personId,setPersonId]=useState(initialPersonId); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(""); const [message,setMessage]=useState("");
 const load=useCallback(async(id?:string)=>{setLoading(true);const target=id||initialPersonId;const res=await fetch(`/api/operator-money${target?`?personId=${target}`:""}`,{cache:"no-store"});const json=await res.json();setLoading(false);if(!res.ok){setMessage(json.error||"Could not load ledger");return;}setData(json);setPersonId(json.selectedPersonId||target||json.currentPersonId||json.team?.[0]?.id||"");},[initialPersonId]);
 useEffect(()=>{void load(initialPersonId);},[initialPersonId,load]);
 const post=async(action:string,body:Row)=>{setSaving(action);setMessage("");const res=await fetch("/api/operator-money",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,personId,...body,clientSubmissionId:body.clientSubmissionId||`${action}:${crypto.randomUUID()}`})});const json=await res.json();setSaving("");if(!res.ok){setMessage(json.error||"Save failed");return false;}setMessage("Saved successfully.");await load(personId);return true;};
 const balance=useMemo(()=>data?.balances.find(x=>x.person_id===personId),[data,personId]);
 if(loading&&!data)return <div className="surface-card">Loading money and debt details…</div>; if(!data)return <div className="surface-card text-red-700">{message||"Money and debt details are unavailable."}</div>;
 const submit=(action:string,extra?:Row)=>(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const body=Object.fromEntries(f.entries());void post(action,{...body,...extra}).then(ok=>{if(ok)form.reset();});};
 return <div className="space-y-5">
  {message?<div className="rounded-lg border border-slate-200 bg-white p-3 text-sm">{message}</div>:null}
  {data.manager&&!lockPerson?<div className="surface-card"><label className="text-sm font-semibold">Operator/person</label><select className="input mt-2" value={personId} onChange={e=>{setPersonId(e.target.value);void load(e.target.value);}}>{data.team.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></div>:null}
  <div className="grid gap-3 md:grid-cols-5">{[["Personal debt",balance?.personal_debt_remaining_lyd],["Money advanced",balance?.advanced_lyd],["Approved expenses",balance?.approved_expenses_lyd],["Money returned",balance?.returned_money_lyd],["Must account for",balance?.unaccounted_advance_lyd]].map(([l,v])=><div className="surface-card" key={String(l)}><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{money(v)}</div></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-3">
   <section className="surface-card"><h2 className="font-semibold">Personal purchase from storage</h2><p className="mt-1 text-xs text-slate-500">This is a personal purchase, not route stock. It uses the normal selling price and adds the total to this person's debt.</p><PurchaseForm products={data.products} saving={saving==="purchase"} onPost={post}/></section>
   <section className="surface-card"><h2 className="font-semibold">Give money to operator</h2>{data.manager?<form className="mt-3 space-y-2" onSubmit={submit("advance")}><MoneyInput/><input className="input" name="purpose" required placeholder="Purpose"/><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><textarea className="input" name="note" placeholder="Optional note"/><button className="btn-primary" disabled={saving==="advance"}>{saving==="advance"?"Saving…":"Record advance"}</button></form>:<p className="mt-3 text-sm text-slate-500">Owner/admin only.</p>}</section>
   <section className="surface-card"><h2 className="font-semibold">Record work expense</h2><p className="mt-1 text-xs text-slate-500">Use this only for money spent on Snacky work, not personal purchases.</p><form className="mt-3 space-y-2" onSubmit={submit("expense")}><MoneyInput/><input className="input" name="expenseType" required placeholder="Expense type"/><input className="input" name="supplierPayee" required placeholder="Supplier/payee"/><select className="input" name="advanceId"><option value="">No related advance</option>{data.advances.filter(x=>x.person_id===personId).map(x=><option value={x.id} key={x.id}>{x.purpose} — {money(x.amount_lyd)}</option>)}</select><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><input className="input" name="receiptUrl" placeholder="Receipt URL (optional)"/><textarea className="input" name="note" required placeholder="What was purchased or paid?"/><button className="btn-primary" disabled={saving==="expense"}>{saving==="expense"?"Submitting…":"Submit expense"}</button></form></section>
  </div>
  {data.manager?<div className="grid gap-4 md:grid-cols-2"><section className="surface-card"><h2 className="font-semibold">Record debt payment</h2><form className="mt-3 space-y-2" onSubmit={submit("debtPayment")}><MoneyInput/><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><input className="input" name="paymentMethod" required placeholder="Payment method"/><textarea className="input" name="note" placeholder="Optional note"/><button className="btn-primary">Mark payment</button></form></section><section className="surface-card"><h2 className="font-semibold">Record money returned</h2><form className="mt-3 space-y-2" onSubmit={submit("advanceReturn")}><MoneyInput/><select className="input" name="advanceId"><option value="">General return</option>{data.advances.filter(x=>x.person_id===personId).map(x=><option value={x.id} key={x.id}>{x.purpose}</option>)}</select><input className="input" name="date" type="datetime-local" defaultValue={nowLocal()} required/><input className="input" name="paymentMethod" required placeholder="Method"/><textarea className="input" name="note" placeholder="Optional note"/><button className="btn-primary">Record return</button></form></section></div>:null}
  <History data={data} personId={personId} manager={data.manager} post={post}/>
 </div>;
}
function MoneyInput(){return <input className="input" name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount (LYD)"/>}
function PurchaseForm({products,saving,onPost}:{products:Row[];saving:boolean;onPost:(a:string,b:Row)=>Promise<boolean>}){const [productId,setProductId]=useState("");const [price,setPrice]=useState(0);const [qty,setQty]=useState(1);const [locations,setLocations]=useState<Row[]>([]);useEffect(()=>{const p=products.find(x=>x.id===productId);setPrice(Number(p?.current_selling_price_lyd??p?.selling_price??0));if(productId)fetch("/api/operator-money",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"availability",productId})}).then(r=>r.json()).then(j=>setLocations(j.data??[]));},[productId,products]);return <form className="mt-3 space-y-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void onPost("purchase",Object.fromEntries(f.entries())).then(ok=>{if(ok){setProductId("");setQty(1);setLocations([]);}});}}><select className="input" name="productId" value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" name="storageLocationId" required><option value="">Select available storage</option>{locations.filter(x=>x.available_qty>0).map(x=><option value={x.storage_location_id} key={x.storage_location_id}>{x.storage_name} — {x.available_qty} available</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="input" name="quantity" type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><input className="input" name="unitPrice" type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></div><div className="rounded bg-slate-50 p-3 font-semibold">Total: {money(qty*price)}</div><textarea className="input" name="note" placeholder="Optional note"/><button className="btn-primary" disabled={saving}>{saving?"Confirming…":"Confirm personal purchase"}</button></form>}
function History({data,personId,manager,post}:{data:Snapshot;personId:string;manager:boolean;post:(a:string,b:Row)=>Promise<boolean>}){const expenses=data.expenses.filter(x=>x.person_id===personId);return <section className="surface-card"><h2 className="font-semibold">Money and debt history</h2><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-2">Type</th><th className="p-2">Details</th><th className="p-2">Amount</th><th className="p-2">Status/date</th><th className="p-2">Action</th></tr></thead><tbody>{data.purchases.filter(x=>x.person_id===personId).map(x=><tr key={x.id} className="border-t"><td className="p-2">Personal purchase</td><td className="p-2">{x.product?.name??"Product"} × {x.quantity}</td><td className="p-2">{money(x.total_lyd)}</td><td className="p-2">{new Date(x.purchased_at).toLocaleString()}</td><td/></tr>)}{data.advances.filter(x=>x.person_id===personId).map(x=><tr key={x.id} className="border-t"><td className="p-2">Advance</td><td className="p-2">{x.purpose}</td><td className="p-2">{money(x.amount_lyd)}</td><td className="p-2">{new Date(x.given_at).toLocaleString()}</td><td/></tr>)}{expenses.map(x=><tr key={x.id} className="border-t"><td className="p-2">Expense</td><td className="p-2">{x.expense_type} — {x.supplier_payee}</td><td className="p-2">{money(x.amount_lyd)}</td><td className="p-2">{x.status}</td><td className="p-2">{manager&&x.status==="submitted"?<div className="flex gap-2"><button className="btn-secondary" onClick={()=>void post("reviewExpense",{expenseId:x.id,status:"approved"})}>Approve</button><button className="btn-secondary" onClick={()=>void post("reviewExpense",{expenseId:x.id,status:"rejected"})}>Reject</button></div>:null}</td></tr>)}</tbody></table></div></section>}