// Runs the already-built production app against the disposable loopback backend.
// Called after browser.mjs; no production credentials or business data are used.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,openSync} from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {createClient} from '@supabase/supabase-js';
const require=createRequire(import.meta.url),{chromium}=require('../../.qa/browser/node_modules/playwright'),AxeBuilder=require('../../.qa/browser/node_modules/@axe-core/playwright').default;
const out='diagnostics/crm-lead-focus';mkdirSync(out,{recursive:true});
const status=Object.fromEntries(readFileSync('.qa/local-status.env','utf8').split('\n').map(l=>l.match(/^([A-Z_]+)="(.*)"$/)).filter(Boolean).map(m=>[m[1],m[2]]));
assert.equal(new URL(status.API_URL).hostname,'127.0.0.1');assert.equal(new URL(status.API_URL).port,'54321');
assert.ok(status.ANON_KEY&&status.SERVICE_ROLE_KEY);
const app='http://localhost:3000',env={...process.env,NEXT_PUBLIC_SNACKY_LEAD_FOCUS_ENABLED:'true',NEXT_PUBLIC_SUPABASE_URL:status.API_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY:status.ANON_KEY,SUPABASE_SERVICE_ROLE_KEY:status.SERVICE_ROLE_KEY,NEXT_PUBLIC_APP_URL:app};
const pg={...process.env,PGHOST:'127.0.0.1',PGPORT:'54322',PGUSER:'postgres',PGDATABASE:'postgres',PGPASSWORD:'postgres'};
function sql(q){const r=spawnSync('psql',['-X','-At','-v','ON_ERROR_STOP=1','-c',q],{env:pg,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();}
const admin=createClient(status.API_URL,status.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),accounts={},password=`Isolated-${randomUUID()}-A9!`;
for(const role of ['owner','crm','other','operator']){
 const actualRole=role==='other'?'crm':role,email=`quick-${role}@example.invalid`,u=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(u.error);
 const id=u.data.user.id,member=randomUUID();
 assert.ifError((await admin.from('team_members').insert({id:member,auth_user_id:id,full_name:`Quick ${role}`,email,role:actualRole,roles:[actualRole],active:true,active_status:'active'})).error);
 assert.ifError((await admin.from('profiles').upsert({id,team_member_id:member,full_name:`Quick ${role}`,email,role:actualRole,roles:[actualRole],active_status:'active',must_change_password:false})).error);
 const client=createClient(status.API_URL,status.ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});assert.ifError((await client.auth.signInWithPassword({email,password})).error);accounts[role]={id,member,email,client};
}
const privateId=randomUUID(),declinedId=randomUUID();
assert.ifError((await admin.from('location_pipeline_leads').insert([{id:privateId,place_name:'Private quick fixture',status:'interested',visibility:'assigned',assigned_to_user_id:accounts.other.member,created_by_member_id:accounts.other.member},{id:declinedId,place_name:'Declined quick fixture',status:'rejected',visibility:'team',assigned_to_user_id:accounts.owner.member,created_by_member_id:accounts.owner.member}])).error);
async function record(id,role='owner'){const r=await accounts[role].client.rpc('snacky_crm_workspace_v1',{p_section:'lead',p_id:id,p_filters:{}});assert.ifError(r.error);return r.data;}
const ledger=()=>sql("select jsonb_build_object('routes',(select count(*) from public.routes),'inventory',(select count(*) from public.inventory_movements),'finance',(select count(*) from public.financial_transactions))::text"),baseline=ledger();
const results=[],pageErrors=[];let browser,server,quickId;
async function check(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',message:String(e.message).slice(0,1600)});let i=0;for(const c of browser?.contexts()??[])for(const p of c.pages())try{await p.screenshot({path:`${out}/quick-failure-${results.length}-${++i}.png`,fullPage:true});}catch{}console.error('FAIL '+name+': '+e.message);}finally{writeFileSync(out+'/quick-results.json',JSON.stringify({results,pageErrors},null,2));}}
try{
 server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3000'],{env,stdio:['ignore',openSync('diagnostics/quick-server.log','w'),openSync('diagnostics/quick-server-errors.log','w')]});
 for(let i=0;i<60;i++){try{if((await fetch(app+'/login')).ok)break;}catch{}await new Promise(r=>setTimeout(r,500));if(i===59)throw Error('Server unavailable');}
 browser=await chromium.launch({headless:true});
 async function session(role,locale='en',width=1440){const c=await browser.newContext({viewport:{width,height:1000}});await c.addCookies([{name:'snacky_os_language',value:locale,url:app}]);const p=await c.newPage();p.setDefaultTimeout(15000);p.setDefaultNavigationTimeout(30000);p.on('pageerror',e=>pageErrors.push(e.message));await p.goto(app+'/login');await p.locator('input[name=email]').fill(accounts[role].email);await p.locator('input[name=password]').fill(password);await Promise.all([p.waitForURL(u=>!u.pathname.startsWith('/login')),p.locator('form button[type=submit]').click()]);return p;}
 const owner=await session('owner'),crm=await session('crm'),operator=await session('operator'),arabic=await session('owner','ar',390);
 const table=p=>p.locator('#crm-leads table');
 const go=async(p,query='')=>{await p.goto(app+'/locations-pipeline?'+query);await p.locator('#crm-leads').waitFor();};
 const openQuick=async()=>{await go(owner,'q=Quick+actions+fixture&group=active');await table(owner).getByRole('button',{name:'Quick update — Quick actions fixture',exact:true}).click();const panel=owner.getByRole('dialog');await panel.getByRole('button',{name:'Log contact',exact:true}).waitFor();return panel;};
 const saveResponse=()=>owner.waitForResponse(r=>r.url().endsWith('/api/crm/command')&&r.request().postDataJSON()?.recordId===quickId);
 const finish=async panel=>{await panel.getByRole('button',{name:'Done — return to work',exact:true}).click();await owner.waitForURL(u=>!u.searchParams.has('quick'));};
 await check('default Open opportunities excludes declined records but explicit Declined retains them',async()=>{await owner.goto(app+'/locations-pipeline');await owner.locator('#crm-leads').waitFor();assert.equal(await table(owner).getByText('Declined',{exact:true}).count(),0);assert.equal(await owner.getByRole('link',{name:'Open opportunities',exact:true}).getAttribute('aria-current'),'page');await owner.getByRole('link',{name:'Declined',exact:true}).click();await owner.waitForURL(u=>u.searchParams.get('group')==='declined');await table(owner).getByRole('link',{name:'Declined quick fixture',exact:true}).waitFor();});
 await check('quick activity saves a real audited result from the table and retains filters',async()=>{
  const made=await accounts.owner.client.rpc('snacky_crm_command_v1',{p_command_id:randomUUID(),p_action:'lead.save',p_id:null,p_payload:{place_name:'Quick actions fixture',notes:'Preserve this context'}});assert.ifError(made.error);quickId=made.data.id;
  const panel=await openQuick();await panel.getByRole('textbox',{name:'What happened and what was the outcome?',exact:true}).fill('Synthetic call outcome: office asked for a follow-up.');const response=saveResponse();await panel.getByRole('button',{name:'Save activity',exact:true}).click();assert.equal((await(await response).json()).ok,true);await finish(panel);assert.equal(new URL(owner.url()).searchParams.get('q'),'Quick actions fixture');const r=await record(quickId);assert.ok(r.activities.some(a=>a.summary.includes('Synthetic call outcome')));assert.equal(r.record.status,'want_to_contact');
 });
 await check('next action and contact saves are partial native edits, not duplicate work',async()=>{
  let panel=await openQuick();await panel.getByRole('button',{name:'Next step',exact:true}).click();await panel.getByRole('textbox',{name:'Next action',exact:true}).fill('Send approved presentation');const date=sql("select (now() at time zone 'Africa/Tripoli')::date+3");await panel.locator('input[name=next_action_date]').fill(date);let response=saveResponse();await panel.getByRole('button',{name:'Save changes',exact:true}).click();assert.equal((await(await response).json()).ok,true);await finish(panel);let r=(await record(quickId)).record;assert.equal(r.next_action,'Send approved presentation');assert.equal(r.due_date,date);
  panel=await openQuick();await panel.getByRole('button',{name:'Contact details',exact:true}).click();await panel.getByRole('textbox',{name:'Contact at the place',exact:true}).fill('Fixture administrator');await panel.getByRole('textbox',{name:'Phone',exact:true}).fill('0917654321');response=saveResponse();await panel.getByRole('button',{name:'Save changes',exact:true}).click();assert.equal((await(await response).json()).ok,true);await finish(panel);r=(await record(quickId)).record;assert.equal(r.data.contact_person_name,'Fixture administrator');assert.equal(r.data.contact_phone,'0917654321');assert.equal(r.next_action,'Send approved presentation');
 });
 await check('decline and lost-save response recover even when the open filtered list becomes empty',async()=>{
  let panel=await openQuick();await panel.getByRole('button',{name:'Change stage',exact:true}).click();await panel.getByRole('combobox',{name:'Stage',exact:true}).selectOption('rejected');await panel.getByRole('textbox',{name:'Reason / outcome',exact:true}).fill('Fixture manager declined because there is no space');await panel.locator('input[name=confirm]').check();
  let request,receipt;await owner.route('**/api/crm/command',async route=>{request=route.request().postDataJSON();const r=await route.fetch();receipt=await r.json();if(receipt.ok)await route.abort('failed');else await route.fulfill({response:r});},{times:1});await panel.getByRole('button',{name:'Save changes',exact:true}).click();await panel.getByText('Save is unconfirmed. Retry the same saved request.',{exact:true}).waitFor();assert.equal(receipt.ok,true);const r=(await record(quickId)).record;assert.equal(r.status,'rejected');assert.match(r.data.notes,/no space/);assert.match(r.data.notes,/Preserve this context/);
  await owner.reload();panel=owner.getByRole('dialog');await panel.getByRole('button',{name:'Retry saved request',exact:true}).waitFor();const count=sql(`select count(*) from public.crm_activities where lead_id='${quickId}'`);const response=saveResponse();await panel.getByRole('button',{name:'Retry saved request',exact:true}).click();const recovered=await response;assert.deepEqual(recovered.request().postDataJSON(),request);assert.equal((await recovered.json()).ok,true);assert.equal(sql(`select count(*) from public.crm_activities where lead_id='${quickId}'`),count);await finish(panel);await owner.getByRole('heading',{name:'No matching leads',exact:true}).waitFor();
 });
 await check('private and operator access denied; closed detail clearly separates ongoing prospecting',async()=>{
  assert.equal((await crm.request.get(app+'/api/crm/leads/'+privateId+'/quick')).status(),403);assert.equal((await operator.request.get(app+'/api/crm/leads/'+quickId+'/quick')).status(),403);await owner.goto(app+'/locations-pipeline/'+quickId);await owner.getByText('Not an active sales opportunity',{exact:true}).waitFor();assert.equal(await owner.locator('a[href*="quick_action=next"]').count(),0);await owner.getByRole('link',{name:'Change stage',exact:true}).click();await owner.getByRole('dialog').getByRole('combobox',{name:'Stage',exact:true}).waitFor();await owner.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await owner.waitForURL(u=>!u.searchParams.has('quick'));
 });
 await check('Arabic mobile and desktop quick panels fit the viewport and pass scoped accessibility',async()=>{
  const captures=[];for(const [p,width,label] of [[owner,1440,'quick-en-1440'],[arabic,390,'quick-ar-390'],[arabic,320,'quick-ar-320']]){
   await p.setViewportSize({width,height:950});await p.goto(app+'/locations-pipeline/'+quickId+'?quick='+quickId+'&quick_action=stage');const panel=p.getByRole('dialog');await panel.getByRole('combobox').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));const a=await new AxeBuilder({page:p}).include('dialog').analyze();captures.push({label,violations:a.violations});await p.screenshot({path:`${out}/${label}.png`,fullPage:false});await panel.getByRole('button',{name:label.startsWith('quick-en')?'Close':'إغلاق',exact:true}).click();await p.waitForURL(u=>!u.searchParams.has('quick'));await p.screenshot({path:`${out}/detail-${label}.png`,fullPage:false});
  }writeFileSync(out+'/quick-accessibility.json',JSON.stringify(captures,null,2));assert.equal(captures.flatMap(a=>a.violations).length,0);
 });
 assert.equal(ledger(),baseline);assert.deepEqual(pageErrors,[]);assert.equal(results.filter(r=>r.status!=='passed').length,0,'Every quick-action acceptance must pass');
}finally{await browser?.close();server?.kill('SIGTERM');if(server)await new Promise(r=>{server.once('exit',r);setTimeout(r,2000);});writeFileSync(out+'/quick-results.json',JSON.stringify({results,pageErrors},null,2));}
