import Link from 'next/link';
import {crmStatus,crmContactLink} from '@/lib/crm-workspace';
import {leadIsClosed} from '@/lib/crm-lead-quick';
import {leadDate} from '@/lib/crm-lead-list';
import styles from './CrmLeadSummary.module.css';
type Props={id:string;status:string;assignedName:string;nextAction?:string|null;dueDate?:string|null;dueTime?:string|null;canEdit:boolean;manager:boolean;ar:boolean;data:Record<string,unknown>};
export function CrmLeadSummary({id,status,assignedName,nextAction,dueDate,dueTime,canEdit,manager,ar,data}:Props){
 const tr=(en:string,arabic:string)=>ar?arabic:en,closed=leadIsClosed(status),text=(v:unknown)=>typeof v==='string'?v:'';
 const contact=text(data.contact_person_name),phone=text(data.contact_phone),area=text(data.area)||text(data.city),location=text(data.converted_location_id);
 return <section className={styles.summary} aria-label={tr('Place overview','ملخص الجهة')}>
  <div className={styles.statusLine}><strong className={status==='rejected'?styles.declined:styles.badge}>{crmStatus(status,ar)}</strong><span>{area||tr('Area not recorded','المنطقة غير مسجلة')}</span></div>
  {closed?<div className={styles.closed}><strong>{status==='rejected'?tr('Not an active sales opportunity','ليست فرصة مبيعات نشطة'):tr('Installation recorded','تم تسجيل التركيب')}</strong><p>{status==='rejected'?tr('Keep the reason and history. Only reopen after a genuine new opportunity.','احتفظ بالسبب والسجل. أعد فتحها فقط عند وجود فرصة جديدة فعلية.'):tr('Ongoing service belongs in the existing location record, not a new sales lead.','تُتابع الخدمة في سجل الموقع الحالي، وليس في جهة مبيعات جديدة.')}</p>{status==='machine_placed'&&location?<Link href={`/relationships/${location}`}>{tr('Open location','فتح الموقع')}</Link>:null}</div>:null}
  <div className={styles.grid}><div><h2>{tr('Assigned to','الموظف المسؤول')}</h2><p>{assignedName}</p></div><div><h2>{tr('Contact at the place','الشخص المسؤول في الجهة')}</h2><p>{contact||tr('Needs research','يحتاج جمع معلومات')}</p>{phone?<span dir="ltr">{phone}</span>:null}</div>{!closed?<div className={styles.next}><h2>{tr('Next action','الخطوة القادمة')}</h2><p>{nextAction||tr('Set a clear next step','حدّد الخطوة القادمة')}</p><span>{leadDate(dueDate,ar)}{dueTime?' · '+dueTime.slice(0,5):''}</span></div>:null}</div>
  <div className={styles.actions}>{canEdit?(['log',...(!closed?['next']:[]),'stage','contact',...(manager?['assign']:[])] as const).map(mode=><Link key={mode} scroll={false} prefetch={false} className={mode==='log'?styles.primary:styles.secondary} href={`/locations-pipeline/${id}?quick=${id}&quick_action=${mode}`}>{({log:tr('Log contact','تسجيل تواصل'),next:tr('Next step','الخطوة القادمة'),stage:tr('Change stage','تغيير المرحلة'),contact:tr('Contact details','بيانات التواصل'),assign:tr('Assign','إسناد')} as Record<string,string>)[mode]}</Link>):null}</div>
  <div className={styles.links}>{(['phone','whatsapp','email'] as const).map(kind=>{const value=kind==='phone'?phone:kind==='whatsapp'?(text(data.contact_whatsapp)||phone):text(data.contact_email),url=crmContactLink(kind,value);return url?<a href={url} key={kind} target={kind==='whatsapp'?'_blank':undefined} rel="noopener noreferrer">{kind==='phone'?tr('Call','اتصال'):kind==='email'?tr('Email','البريد الإلكتروني'):'WhatsApp'}</a>:null;})}<a href="#lead-history">{tr('Activity history','سجل النشاط')}</a><a href="#lead-files">{tr('Files & evidence','الملفات والإثباتات')}</a>{canEdit?<Link href={`/locations-pipeline/${id}?edit=1#lead-edit`}>{tr('Full edit form','نموذج التعديل الكامل')}</Link>:null}</div>
  {text(data.notes)?<details className={styles.notes}><summary>{tr('Notes & previous outcomes','الملاحظات والنتائج السابقة')}</summary><p>{text(data.notes)}</p></details>:null}
 </section>;
}
