/* eslint-disable @typescript-eslint/no-explicit-any */
import { CrmForm } from '@/components/CrmForm';
import { crmNames,crmOptionRows,issueCategories,issueStatuses,leadStatuses,locationTypes,taskStatuses,type CrmField,type CrmKind } from '@/lib/crm-workspace';

type Context={me:string;manager:boolean;owner_admin:boolean;staff:boolean;today:string;directory:any[];options:any};
export function CrmRecordForm({kind,row,context,userId,ar}:{kind:CrmKind;row?:any;context:Context;userId:string;ar:boolean}){
 const tr=(en:string,arabic:string)=>ar?arabic:en,d=row?.data??{},relation=d.relationship??{};
 const f=(name:string,en:string,arabic:string,extra:Partial<CrmField>={}):CrmField=>({name,label:tr(en,arabic),value:String(d[name]??''),...extra});
 const people=(field=false)=>context.directory.filter(p=>field||p.role!=='operator').map(p=>({value:p.id,label:p.name}));
 const assignee=f('assigned_to','Responsible employee','الموظف المسؤول',{type:'select',value:row?.assigned_to??context.me,options:people(kind==='task'),required:true});
 const next=[f('next_action','Next action','الخطوة القادمة'),f('next_action_date','Next follow-up date','تاريخ المتابعة القادمة',{type:'date'}),f('next_action_time','Time (optional)','الوقت (اختياري)',{type:'time',advanced:true})];
 const locationOptions=[{value:'',label:tr('Choose location','اختر الموقع')},...(context.options.locations??[]).map((x:any)=>({value:x.id,label:x.name}))];
 let fields:CrmField[]=[];
 if(kind==='lead'){
  const statusOptions=crmOptionRows(leadStatuses,ar);if(d.status&&!statusOptions.some(o=>o.value===d.status))statusOptions.push({value:d.status,label:d.status});
  fields=[f('place_name','Place name','اسم الجهة',{required:true}),f('place_type','Type','النوع',{type:'select',value:d.place_type??'other',options:crmOptionRows(locationTypes,ar)}),f('contact_phone','Phone','الهاتف',{type:'tel'}),f('contact_person_name','Contact person','اسم المسؤول'),assignee,...next.filter(x=>!x.advanced),f('notes','Conversation / visit notes','ملاحظات التواصل أو الزيارة',{type:'textarea'}),
   f('status','Status','الحالة',{type:'select',value:d.status??'want_to_contact',options:statusOptions,advanced:!row}),f('area','Area','المنطقة',{advanced:true}),f('city','City','المدينة',{advanced:true}),f('address_text','Address','العنوان',{advanced:true}),f('name_ar','Arabic name (if different)','الاسم بالعربية (إن اختلف)',{advanced:true}),f('contact_person_job_title','Position / title','الصفة أو المنصب',{advanced:true}),f('contact_whatsapp','WhatsApp','واتساب',{type:'tel',advanced:true}),f('contact_email','Email','البريد الإلكتروني',{type:'email',advanced:true}),f('reception_phone','Reception / general phone','رقم الاستقبال / الرقم العام',{type:'tel',advanced:true}),f('google_maps_url','Map URL','رابط الموقع',{type:'url',advanced:true}),f('website','Website','الموقع الإلكتروني',{type:'url',advanced:true}),f('social_links','Social links','روابط التواصل الاجتماعي',{advanced:true}),f('estimated_traffic','Estimated daily traffic','الحركة اليومية التقديرية',{type:'number',min:0,step:'1',advanced:true}),f('attraction_notes','Why this place is attractive','لماذا هذه الجهة مناسبة؟',{type:'textarea',advanced:true}),f('rent_expectation','Requested rent — not an agreed expense','الإيجار المطلوب — ليس مصروفاً معتمداً',{type:'number',min:0,advanced:true}),
   f('source','Source','مصدر الجهة',{type:'select',value:d.source??'manual',advanced:true,options:crmOptionRows([['manual','Employee research','بحث الموظف'],['owner','Snacky management','إدارة سناكي'],['customer_support','Customer support','خدمة العملاء'],['field_outreach','Field outreach','زيارة ميدانية'],['inbound','Website / social inquiry','استفسار الموقع / التواصل'],['referral','Referral','ترشيح'],['archive_import','Imported archive','أرشيف مستورد'],['other','Other','أخرى']],ar)}),f('source_detail','Source details','تفاصيل المصدر',{advanced:true}),next[2],f('visibility','Who can view this lead?','من يمكنه عرض الجهة؟',{type:'select',value:d.visibility??'team',advanced:true,options:crmOptionRows([['team','Customer relations team','فريق علاقات العملاء'],['assigned','Assigned employee and management','الموظف المسؤول والإدارة']],ar)})];
 }
 if(kind==='issue'){
  fields=[f('customer_phone','Customer phone','هاتف العميل',{type:'tel',required:!row}),f('location_id','Location','الموقع',{type:'select',value:d.location_id??row?.location_id??'',options:locationOptions,required:!row}),f('description','What happened?','ما المشكلة؟',{type:'textarea',required:true}),assignee,f('issue_type','Category','نوع المشكلة',{type:'select',value:d.issue_type??'other',options:crmOptionRows(issueCategories,ar)}),f('amount_involved_lyd','Amount involved (LYD)','المبلغ المتعلق بالمشكلة (د.ل)',{type:'number',min:0}),f('status','Status','الحالة',{type:'select',value:row?.status??'open',options:crmOptionRows(issueStatuses,ar)}),f('waiting_on','Waiting for whom / what?','بانتظار من أو ماذا؟',{hint:tr('Required only when Waiting.','مطلوب فقط في حالة الانتظار.')}),f('next_action','Next action','الخطوة القادمة'),f('next_action_date','Follow up on','تاريخ المتابعة',{type:'date',value:d.next_action_date??context.today}),
   f('customer_name','Customer name (optional)','اسم العميل (اختياري)',{advanced:!row}),f('customer_whatsapp','WhatsApp','واتساب',{type:'tel',advanced:true}),f('contact_channel','Preferred contact channel','طريقة التواصل المفضلة',{type:'select',value:d.contact_channel??'phone',options:crmOptionRows([['phone','Phone','هاتف'],['whatsapp','WhatsApp','واتساب'],['email','Email','بريد إلكتروني'],['other','Other','أخرى']],ar),advanced:true}),f('machine_id','Machine (optional)','الماكينة (اختياري)',{type:'select',options:[{value:'',label:tr('Not identified yet','لم يتم تحديدها')},...(context.options.machines??[]).map((m:any)=>({value:m.id,label:m.name}))],advanced:true}),f('lane_number','Product / lane number','رقم المنتج / المسار',{advanced:true}),f('happened_at','When the problem happened','وقت حدوث المشكلة',{type:'datetime-local',value:d.happened_at?new Date(d.happened_at).toLocaleString('sv-SE',{timeZone:'Africa/Tripoli'}).slice(0,16).replace(' ','T'):'',advanced:true}),f('priority','Priority','الأولوية',{type:'select',value:d.priority??'normal',options:crmOptionRows([['normal','Normal','عادية'],['high','High','عالية'],['critical','Critical','حرجة'],['low','Low','منخفضة']],ar),advanced:true})];
  if(row)fields.push(f('resolution','Resolution / customer outcome','الحل ونتيجة التواصل مع العميل',{type:'textarea',hint:tr('Required to resolve. Field completion alone does not close a complaint.','مطلوب لإغلاق المشكلة. انتهاء الفحص الميداني لا يغلقها تلقائياً.')}),f('refund_amount_lyd','Refund reported (LYD)','المبلغ المسترد المسجّل (د.ل)',{type:'number',min:0,hint:tr('Records the resolution; this does not create a Finance payment.','يسجّل نتيجة الحل ولا ينشئ دفعة مالية.')}));
 }
 if(kind==='contact')fields=[f('name','Name','الاسم',{required:true}),f('phone','Phone','الهاتف',{type:'tel'}),f('organization','Organization','الجهة'),f('position','Position','الصفة'),f('whatsapp','WhatsApp','واتساب',{type:'tel'}),f('email','Email','البريد الإلكتروني',{type:'email'}),f('preferred_channel','Preferred channel','طريقة التواصل',{type:'select',value:d.preferred_channel??'phone',options:crmOptionRows([['phone','Phone','هاتف'],['whatsapp','WhatsApp','واتساب'],['email','Email','بريد إلكتروني'],['other','Other','أخرى']],ar)}),f('notes','Notes','ملاحظات',{type:'textarea'})];
 if(kind==='task'){
  fields=context.staff?[f('title','Task','المهمة',{required:true}),assignee,f('due_date','Due date','تاريخ الاستحقاق',{type:'date',value:d.due_date??context.today,required:true}),f('due_time','Time (optional)','الوقت (اختياري)',{type:'time'}),f('priority','Priority','الأولوية',{type:'select',value:d.priority??'normal',options:crmOptionRows([['low','Low','منخفضة'],['normal','Normal','عادية'],['high','High','عالية'],['urgent','Urgent','عاجلة']],ar)}),f('notes','Instructions','التعليمات',{type:'textarea'})]:[];
  if(row)fields.push(f('status','Status','الحالة',{type:'select',value:d.status??'open',options:crmOptionRows(taskStatuses,ar)}),f('result','Work performed / result','العمل المنجز والنتيجة',{type:'textarea',hint:tr('A result is required before completing the task.','يجب كتابة النتيجة قبل إكمال المهمة.')}));
 }
 if(kind==='location'){
  fields=[...next.map(x=>({...x,value:relation[x.name]??''})),f('notes','Relationship notes','ملاحظات العلاقة',{type:'textarea',value:relation.notes??''})];
  if(context.manager)fields.push({...assignee,value:relation.assigned_to??context.me},f('agreement_type','Agreement type','نوع الاتفاق',{type:'select',value:relation.agreement_type??'other',options:crmOptionRows([['fixed_rent','Fixed rent','إيجار ثابت'],['revenue_share','Revenue share','نسبة من الإيراد'],['free_service','No rent','دون إيجار'],['other','Other / not recorded','أخرى / غير مسجل']],ar)}),f('payment_frequency','Frequency','تكرار الدفع',{type:'select',value:relation.payment_frequency??'monthly',options:crmOptionRows([['once','Once','مرة واحدة'],['monthly','Monthly','شهري'],['quarterly','Quarterly','ربع سنوي'],['yearly','Yearly','سنوي']],ar)}));
 }
 if(kind==='obligation')fields=[f('title','Obligation','الالتزام',{value:'',required:true}),f('location_id','Location','الموقع',{type:'select',options:locationOptions,required:true}),f('amount_lyd','Amount (LYD)','المبلغ (د.ل)',{type:'number',min:0,required:true}),f('due_date','Due date','تاريخ الاستحقاق',{type:'date',required:true}),assignee,f('frequency','Frequency','التكرار',{type:'select',value:'monthly',options:crmOptionRows([['once','Once','مرة واحدة'],['monthly','Monthly','شهري'],['quarterly','Quarterly','ربع سنوي'],['yearly','Yearly','سنوي']],ar)}),f('notes','Notes','ملاحظات',{type:'textarea'})];
 if(!row&&context.manager&&['lead','issue','obligation'].includes(kind))fields.push(f('is_practice','Practice record — excluded from real work reports','سجل تدريبي — مستبعد من تقارير العمل الفعلي',{type:'checkbox',value:'false',advanced:true}));
 return <CrmForm key={`${kind}:${row?.id??'new'}:${d.version??''}`} action={kind==='obligation'?'obligation.create':`${kind}.save`} recordId={row?.id} userId={userId} hidden={row?{version:d.version??''}:{}} fields={fields} submitLabel={row?tr('Save changes','حفظ التغييرات'):tr('Add record','إضافة السجل')}/>;
}

export function CrmFollowupForm({kind,id,context,userId,ar}:{kind:CrmKind;id:string;context:Context;userId:string;ar:boolean}){
 const tr=(en:string,arabic:string)=>ar?arabic:en;
 return <CrmForm action="task.save" userId={userId} hidden={{kind,related_id:id}} fields={[
  {name:'title',label:tr('Next action','الخطوة القادمة'),required:true},
  {name:'task_type',label:tr('Type','النوع'),type:'select',value:kind==='issue'?'field_action':'follow_up',options:crmOptionRows(kind==='issue'?[['field_action','Operator field action','إجراء ميداني للمشغّل'],['follow_up','Customer follow-up','متابعة العميل']]:[['follow_up','Follow-up','متابعة'],['meeting','Meeting / visit','موعد / زيارة'],['admin','Administrative task','مهمة إدارية']],ar)},
  {name:'assigned_to',label:tr('Assigned to','المسؤول'),type:'select',required:true,value:context.me,options:context.directory.filter(p=>kind==='issue'||p.role!=='operator').map(p=>({value:p.id,label:p.name}))},
  {name:'due_date',label:tr('Due date','تاريخ الاستحقاق'),type:'date',required:true,value:context.today},
  {name:'due_time',label:tr('Time (optional)','الوقت (اختياري)'),type:'time'},
  {name:'notes',label:tr('Instructions / context','التعليمات والسياق'),type:'textarea'},
 ]} submitLabel={tr('Assign follow-up','تعيين المتابعة')} stay/>;
}
export function CrmNoteForm({kind,id,userId,ar}:{kind:CrmKind;id:string;userId:string;ar:boolean}){
 return <CrmForm action="note.add" recordId={id} userId={userId} hidden={{kind}} fields={[
  {name:'activity_type',label:ar?'نوع التواصل':'Interaction',type:'select',value:'note',options:crmOptionRows([['note','Note','ملاحظة'],['call','Call','مكالمة'],['whatsapp','WhatsApp','واتساب'],['email','Email','بريد إلكتروني'],['visit','Field visit','زيارة ميدانية'],['meeting','Meeting','اجتماع'],['proposal','Proposal sent','إرسال عرض'],['agreement','Agreement','اتفاق'],['other','Other','أخرى']],ar)},
  {name:'summary',label:ar?'ماذا حدث وما النتيجة؟':'What happened and what was the outcome?',type:'textarea',required:true},
 ]} submitLabel={ar?'حفظ النشاط':'Save activity'} stay/>;
}
