/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getAuthenticatedSupabaseServerClient,getCurrentProfile } from '@/lib/auth';
import { hasAnyRole } from '@/lib/authz';
import { getServerI18n } from '@/lib/i18n/server';
import { ErrorState,PageHeader,EmptyState } from '@/components/ui';
import { CrmForm } from '@/components/CrmForm';
import { CrmDocumentUpload,CrmRefresh,CrmWelcome } from '@/components/CrmClientTools';
import { CrmRecordForm,CrmFollowupForm,CrmNoteForm } from '@/components/CrmRecordForms';
import {CrmLocationPaymentScheduleForm} from '@/components/CrmLocationPaymentScheduleForm';
import {CustomerSupportPanel} from '@/components/CustomerSupportPanel';\nimport {CrmDispatchTaskPanel,CrmIssueDispatchSummary} from '@/components/CrmDispatchPanel';
import { crmContactLink,crmHref,crmNames,crmPaths,crmStatus,crmOptionRows,issueStatuses,leadStatuses,taskStatuses,issueCategories,locationTypes,type CrmKind,type CrmSection } from '@/lib/crm-workspace';

export type CrmSearchParams=Record<string,string|string[]|undefined>;
const scalar=(params:CrmSearchParams,key:string)=>typeof params[key]==='string'?params[key] as string:'';
function formattedDate(value:any,ar:boolean){if(!value)return ar?'غير مسجّل':'Not recorded';const date=new Date(String(value));return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat(ar?'ar-LY':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Tripoli'}).format(date);}
function money(value:unknown){return value===null||value===undefined?'—':`${Number(value).toLocaleString('en-US',{maximumFractionDigits:2})} LYD`;}
function Badge({status,ar,overdue}:{status:string;ar:boolean;overdue?:boolean}){return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${overdue?'border-rose-200 bg-rose-50 text-rose-900':status==='resolved'||status==='completed'?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-slate-200 bg-slate-50 text-slate-700'}`}>{overdue?(ar?'متأخر':'Overdue'):crmStatus(status,ar)}</span>;}
function ContactButtons({row,ar}:{row:any;ar:boolean}){
 const data=row?.data??row??{},phone=data.customer_phone??data.phone??data.contact_phone,whatsapp=data.customer_whatsapp??data.whatsapp??data.contact_whatsapp??phone,email=data.email??data.contact_email;
 return <div className="flex flex-wrap gap-2">{([['phone',phone,ar?'اتصال':'Call'],['whatsapp',whatsapp,'WhatsApp'],['email',email,ar?'بريد إلكتروني':'Email']] as const).map(([kind,value,label])=>{const href=crmContactLink(kind,value);return href?<a key={kind} className="btn-secondary min-h-10 text-xs" href={href} target={kind==='whatsapp'?'_blank':undefined} rel="noopener noreferrer">{label}</a>:null;})}</div>;
}
function RecordRows({rows,ar,staff}:{rows:any[];ar:boolean;staff:boolean}){
 const tr=(en:string,arabic:string)=>ar?arabic:en;
 return <div className="space-y-3">{rows.map(row=><article className={`rounded-xl border bg-white p-4 ${row.overdue?'border-rose-200':'border-slate-200'}`} key={`${row.kind}:${row.id}`}>
  <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-slate-500">{crmNames[row.kind as CrmSection]?.[ar?1:0]??row.kind}{row.is_practice?` · ${tr('PRACTICE','تدريب')}`:''}{row.data?.is_historical?` · ${tr('HISTORICAL','تاريخي')}`:''}</p><Link href={crmHref(row.kind,row.id)} className="mt-1 block break-words font-semibold text-slate-950 hover:underline">{row.title}</Link><p className="mt-1 text-sm text-slate-600">{row.location_name??row.machine_name??''}</p></div><Badge status={row.status} ar={ar} overdue={row.overdue}/></div>
  <div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div><span className="text-xs text-slate-500">{tr('Next action','الخطوة القادمة')}</span><p>{row.data?.is_historical?tr('Historical record — no current action','سجل تاريخي — لا يتطلب إجراء حالياً'):(row.next_action||tr('Not scheduled','لم تُحدد'))}</p></div><div><span className="text-xs text-slate-500">{tr('Due','الموعد')}</span><p dir="ltr" className="text-start">{row.due_date??'—'} {row.due_time?.slice(0,5)??''}</p></div><div><span className="text-xs text-slate-500">{tr('Assigned to','المسؤول')}</span><p>{row.assigned_name??tr('Unassigned','غير معيّن')}</p></div></div>
  {row.kind==='obligation'?<p className="mt-3 text-sm font-medium">{money(row.data.amount_lyd)} · {row.data?.is_historical?tr('Historical paid record — no Finance action','سجل دفع تاريخي — لا يتطلب إجراءً مالياً'):row.data.finance_verified_at?tr('Finance verified','تم التحقق المالي'):row.status==='paid'?tr('Payment reported — Finance not verified','الدفع مسجّل — بانتظار التحقق المالي'):tr('Administrative follow-up','متابعة إدارية')}</p>:null}
  {staff&&['lead','issue','contact'].includes(row.kind)?<div className="mt-3"><ContactButtons row={row} ar={ar}/></div>:null}
 </article>)}</div>;
}

export async function CrmWorkspace({section,id,searchParams={},create=false}:{section:CrmSection;id?:string;searchParams?:CrmSearchParams;create?:boolean}){
 const profile=await getCurrentProfile();
 if(!profile||profile.active_status!=='active'||!hasAnyRole(profile,['owner','admin','supervisor','crm','operator']))redirect('/unauthorized');
 const {locale}=await getServerI18n(),ar=locale==='ar',tr=(en:string,arabic:string)=>ar?arabic:en,db=await getAuthenticatedSupabaseServerClient();
 const filters:Record<string,string>={};for(const key of ['q','scope','window','status','location_id','machine_id','type','area','created_from','created_to','payment_month','assigned_to','offset','history_offset','agreement_type','open_issues','archived','practice']){const v=scalar(searchParams,key);if(v)filters[key]=v;}
 if(section==='work'){filters.scope=filters.scope||'mine';filters.window=filters.window||'attention';}
 if(section==='obligation'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(filters.payment_month??'')){
  const [year,month]=(filters.payment_month as string).split('-').map(Number);
  filters.created_from=`${filters.payment_month}-01`;
  filters.created_to=new Date(Date.UTC(year,month,0)).toISOString().slice(0,10);
 }
 let context:any;
 try{
  if(!db)throw new Error('Session unavailable');
  const result=await db.rpc('snacky_crm_workspace_v1',{p_section:section,p_id:id??null,p_filters:filters});
  if(result.error)throw result.error;if(!result.data||typeof result.data!=='object')throw new Error('Invalid workspace data');context=result.data;
 }catch(error){console.error('[crm-workspace] Could not verify records',{section,error});return <ErrorState title={tr('Customer relations unavailable','علاقات العملاء غير متاحة')} body={tr('Could not verify these records or your access. This is not an empty task list. Reload after the database update or connection is restored.','تعذر التحقق من السجلات أو صلاحياتك. هذا لا يعني عدم وجود مهام. أعد التحميل بعد تحديث قاعدة البيانات أو استعادة الاتصال.')}/>;}
 let support:any=null;
 if(section==='work'&&context.staff&&db){
  const supportResult=await db.rpc('snacky_customer_support_dashboard_v1',{});
  if(!supportResult.error&&supportResult.data&&typeof supportResult.data==='object')support=supportResult.data;
  else console.error('[crm-workspace] Customer support panel unavailable',{error:supportResult.error});
 }
 const row=context.record,d=row?.data??{},kind=section as CrmKind;
 const rows=(context.rows??[]).map((r:any)=>({...r,assigned_name:r.assigned_name??context.directory.find((p:any)=>p.id===r.assigned_to)?.name}));
 const name=(member:any)=>context.directory.find((p:any)=>p.id===member)?.name??(ar?'غير مسجّل':'Not recorded');
 const title=create&&section==='issue'?tr('Quick customer issue','بلاغ عميل سريع'):create?`${tr('Add','إضافة')} ${crmNames[section][ar?1:0]}`:row?.title??(section==='work'?`${tr('Hello','أهلاً')}, ${profile.full_name.split(' ')[0]}`:crmNames[section][ar?1:0]);
 const listHref=crmPaths[section];
 const canCreate=context.staff&&['lead','issue','contact','task'].includes(section)||context.manager&&section==='obligation';
 const detailEdit=row?.can_edit&&!(row.kind==='task'&&d.status==='completed')&&!row.archived;
 const dispatchTasks=(context.tasks??[]).filter((task:any)=>task.task_type==='field_action'&&task.dispatch_state&&task.archived_at===null).map((task:any)=>({...task,assigned_name:name(task.assigned_to)}));
 const taskDispatch=section==='task'&&d.task_type==='field_action'&&d.dispatch_state?{...d,id:row.id,title:row.title,updated_at:d.updated_at??d.version??row.updated_at}:null;
 const taskProofImages=section==='task'?(context.documents??[]).filter((doc:any)=>String(doc.mime_type??'').toLowerCase().startsWith('image/')).length:0;
 const fieldWorkReadyForCrm=section==='issue'&&dispatchTasks.length>0&&dispatchTasks.every((task:any)=>task.dispatch_state==='fixed');
 return <div className="min-w-0 space-y-5" dir={ar?'rtl':'ltr'}>
  <CrmRefresh/>
  <PageHeader title={title} subtitle={row?tr('Ownership, next action and complete relationship history.','المسؤول والخطوة القادمة وسجل العلاقة.'):create&&section==='issue'?tr('Record only the essentials now. After saving, open the case to assign field work, follow up with the customer, record compensation and close it.','سجّلي الأساسيات فقط الآن. بعد الحفظ افتحي الحالة لتعيين إجراء ميداني أو متابعة العميل وتسجيل التعويض ثم إغلاقها.'):tr('External conversations happen by phone, WhatsApp and visits. The outcome and next action live here.','التواصل الخارجي بالمكالمات وواتساب والزيارات. النتيجة والخطوة القادمة تُسجّلان هنا.')} action={row||create?<Link className="btn-secondary" href={listHref}>{tr('Back to list','العودة للقائمة')}</Link>:canCreate?<Link className="btn-primary" href={`${listHref}/new`}>+ {section==='issue'?tr('Add customer issue','إضافة مشكلة عميل'):section==='lead'?tr('Add lead','إضافة جهة'):tr('Add record','إضافة سجل')}</Link>:null}/>
  {section==='work'&&context.staff?<CrmWelcome userId={profile.id}/>:null}
  {section==='work'&&context.staff&&support?<CustomerSupportPanel data={support} ar={ar}/>:null}
  {!row&&!create&&section==='work'?<>
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{[
    ['issue_action','Issues requiring action','مشاكل تحتاج إجراء','/issues?status=open'],['issue_waiting','Waiting on someone else','بانتظار طرف آخر','/issues?status=waiting'],['leads_today','Lead follow-ups today','متابعات الجهات اليوم','/locations-pipeline?window=today'],['leads_overdue','Overdue leads','جهات متأخرة','/locations-pipeline?window=overdue'],['locations_today','Location follow-ups','متابعات المواقع','/relationships?window=today'],['admin_today','Administrative tasks','مهام إدارية','/follow-ups?type=admin&window=today'],['rent_week','Rent / payments due soon','دفعات المواقع القريبة','/relationships/obligations?window=week'],['meetings_today','Meetings today','مواعيد اليوم','/follow-ups?type=meeting&window=today'],['recent_completed','Recently completed','أُنجز مؤخراً','/follow-ups?window=completed']
   ].filter(x=>context.staff||['issue_action','recent_completed'].includes(x[0])).map(([key,en,arabic,href])=><Link key={key} href={`${href}&scope=mine`} className="surface-card block"><span className="text-xs font-medium text-slate-500">{tr(en,arabic)}</span><strong className="mt-2 block text-2xl">{context.counts[key]??0}</strong></Link>)}</div>
   <div className="flex flex-wrap gap-2">{context.staff?<><Link className="btn-primary" href="/issues/new">+ {tr('Quick customer issue','بلاغ عميل سريع')}</Link><Link className="btn-secondary" href="/locations-pipeline/new">+ {tr('Add lead','إضافة جهة')}</Link><Link className="btn-secondary" href="/follow-ups/new">+ {tr('Follow-up','متابعة')}</Link></>:null}{context.manager?<Link className="btn-secondary" href="/my-work/team">{tr('Management view','عرض الإدارة')}</Link>:null}</div>
  </>:null}
  {create?canCreate?<section className="surface-card"><CrmRecordForm kind={kind} context={context} userId={profile.id} ar={ar}/></section>:<ErrorState title={tr('Not permitted','غير مسموح')} body={tr('Your role cannot create this record.','دورك لا يسمح بإنشاء هذا السجل.')}/>:null}
  {!row&&!create?<>
   <form method="get" action={listHref} className="surface-card grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <label className="text-sm">{tr('Search name, phone or notes','البحث بالاسم أو الهاتف أو الملاحظات')}<input name="q" defaultValue={filters.q} className="field-input mt-1" placeholder={tr('Search…','بحث…')}/></label>
    <label className="text-sm">{tr('Ownership','المسؤولية')}<select name="scope" defaultValue={filters.scope??'all'} className="field-input mt-1"><option value="mine">{tr('Mine','المسند إليّ')}</option><option value="all">{tr('All permitted records','كل السجلات المسموح بها')}</option></select></label>
    <label className="text-sm">{tr('When','الوقت')}<select name="window" defaultValue={filters.window??'all'} className="field-input mt-1">{[['all','All','الكل'],['attention','Needs attention','يحتاج متابعة'],['today','Today','اليوم'],['overdue','Overdue','متأخر'],['week','This week','هذا الأسبوع'],['completed','Completed','مكتمل']].map(([v,en,arabic])=><option key={v} value={v}>{tr(en,arabic)}</option>)}</select></label>
    {['lead','issue','task'].includes(section)?<label className="text-sm">{tr('Status','الحالة')}<select name="status" defaultValue={filters.status??''} className="field-input mt-1"><option value="">{tr('All statuses','كل الحالات')}</option>{crmOptionRows(section==='lead'?leadStatuses:section==='issue'?issueStatuses:taskStatuses,ar).map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></label>:null}
    {context.staff?<label className="text-sm">{tr('Assigned employee','الموظف المسؤول')}<select name="assigned_to" defaultValue={filters.assigned_to??''} className="field-input mt-1"><option value="">{tr('Everyone permitted','كل المسؤولين المسموحين')}</option>{context.directory.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:null}
    {context.staff&&['issue','location','obligation'].includes(section)?<label className="text-sm">{tr('Location','الموقع')}<select className="field-input mt-1" name="location_id" defaultValue={filters.location_id??''}><option value="">{tr('All locations','كل المواقع')}</option>{context.options.locations?.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>:null}
    {section==='issue'?<label className="text-sm">{tr('Machine','الماكينة')}<select name="machine_id" defaultValue={filters.machine_id??''} className="field-input mt-1"><option value="">{tr('All machines','كل الماكينات')}</option>{context.options.machines?.filter((m:any)=>!filters.location_id||m.location_id===filters.location_id).map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>:null}
    {['lead','issue','location','task'].includes(section)?<label className="text-sm">{tr('Type / category','النوع / الفئة')}<select name="type" defaultValue={filters.type??''} className="field-input mt-1"><option value="">{tr('All types','كل الأنواع')}</option>{crmOptionRows(section==='issue'?issueCategories:section==='task'?[['follow_up','Follow-up','متابعة'],['field_action','Field action','إجراء ميداني'],['meeting','Meeting / visit','موعد / زيارة'],['admin','Administration','إداري']]:locationTypes,ar).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>:null}
    {section==='location'?<><label className="text-sm">{tr('Agreement type','نوع الاتفاق')}<select className="field-input mt-1" name="agreement_type" defaultValue={filters.agreement_type??''}><option value="">{tr('All agreements','كل الاتفاقيات')}</option>{crmOptionRows([['fixed_rent','Fixed rent','إيجار ثابت'],['revenue_share','Revenue share','نسبة من الإيراد'],['free_service','No rent','دون إيجار'],['other','Other / unknown','أخرى / غير معروف']],ar).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="open_issues" value="true" defaultChecked={filters.open_issues==='true'}/>{tr('Locations with open issues','مواقع بها مشاكل مفتوحة')}</label></>:null}
    {section==='obligation'?<label className="text-sm">{tr('Payment month','شهر الإيجار / الدفع')}<input name="payment_month" type="month" className="field-input mt-1" defaultValue={filters.payment_month??''}/></label>:<>
     <label className="text-sm">{tr('Created from','أُنشئ من')}<input name="created_from" type="date" className="field-input mt-1" defaultValue={filters.created_from??''}/></label>
     <label className="text-sm">{tr('Created through','أُنشئ حتى')}<input name="created_to" type="date" className="field-input mt-1" defaultValue={filters.created_to??''}/></label>
    </>}
    {section==='lead'?<label className="text-sm">{tr('Area','المنطقة')}<input name="area" defaultValue={filters.area} className="field-input mt-1"/></label>:null}
    <div className="flex flex-wrap items-center gap-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" name="archived" value="true" defaultChecked={filters.archived==='true'}/>{tr('Include archived','إظهار المؤرشف')}</label><label className="flex items-center gap-2"><input type="checkbox" name="practice" value="true" defaultChecked={filters.practice==='true'}/>{tr('Include practice','إظهار التدريب')}</label></div>
    <div className="flex items-end gap-2"><button className="btn-primary">{tr('Apply','تطبيق')}</button><Link className="btn-secondary" href={listHref}>{tr('Reset','إعادة ضبط')}</Link></div>
   </form>
   {section==='management'?<section className="surface-card"><h2 className="font-semibold">{tr('Team activity — last 30 days','نشاط الفريق — آخر 30 يوماً')}</h2><p className="mt-2 text-xs text-slate-500">{tr('Activity since this connected workflow was introduced; practice records are excluded. Handled and overdue counts show the current position.','النشاط المسجّل منذ بدء العمل المترابط؛ تُستبعد سجلات التدريب. أعداد المسؤوليات والمتأخرات تمثل الوضع الحالي.')}</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{context.performance?.map((p:any)=><div key={p.id} className="rounded-xl border p-4"><strong>{p.name}</strong><dl className="mt-3 grid grid-cols-2 gap-2 text-sm">{[['issues_handled','Current issues','المشاكل المسندة'],['issues_resolved','Resolved','تم حلها'],['average_resolution_hours','Average hours to resolve','متوسط ساعات الحل'],['leads_contacted','Leads contacted','جهات تم التواصل معها'],['proposals_sent','Proposals sent','العروض المرسلة'],['accepted','Accepted locations','الجهات المقبولة'],['tasks_completed','Tasks completed','المتابعات المكتملة'],['overdue_followups','Overdue follow-ups','المتابعات المتأخرة']].map(([key,en,arabic])=><div key={key}><dt className="text-xs text-slate-500">{tr(en,arabic)}</dt><dd className="font-semibold">{p[key]??'—'}</dd></div>)}</dl></div>)}</div></section>:null}
   <div className="flex justify-between text-sm text-slate-600"><h2 className="font-semibold">{section==='work'?tr('Your work queue','قائمة عملك'):crmNames[section][ar?1:0]}</h2><span>{context.total} {tr('records','سجل')}</span></div>
   {rows.length?<RecordRows rows={rows} ar={ar} staff={context.staff}/>:<EmptyState title={tr('No matching records','لا توجد سجلات مطابقة')} body={tr('No records match these filters. Resolved and completed records remain available through the status and date filters.','لا توجد سجلات بهذه المرشحات. تبقى السجلات المحلولة والمكتملة متاحة من مرشحات الحالة والتاريخ.')}/>}
   <div className="flex justify-between gap-2">{context.offset>0?<Link className="btn-secondary" href={`${listHref}?${new URLSearchParams({...filters,offset:String(Math.max(0,context.offset-40))})}`}>{tr('Previous','السابق')}</Link>:<span/>}{context.offset+40<context.total?<Link className="btn-secondary" href={`${listHref}?${new URLSearchParams({...filters,offset:String(context.offset+40)})}`}>{tr('Next','التالي')}</Link>:null}</div>
   <p className="text-xs text-slate-500">{tr('Refreshes while this page is open. No messages or payments are sent automatically.','تتحدّث البيانات أثناء فتح الصفحة. لا تُرسل رسائل أو دفعات تلقائياً.')}</p>
  </>:null}
  {row&&!create?<>
   <section className="surface-card space-y-4"><div className="flex flex-wrap items-center gap-2"><Badge status={row.status} ar={ar}/>{row.archived?<span className="text-sm text-amber-900">{tr('Archived — history preserved','مؤرشف — السجل محفوظ')}</span>:null}{row.is_practice?<span className="text-sm text-amber-900">{tr('Practice only','للتدريب فقط')}</span>:null}{d.is_historical?<span className="rounded-full border border-violet-200 bg-violet-50 px-2.5 py-1 text-xs font-semibold text-violet-900">{tr('Historical record','سجل تاريخي')}</span>:null}</div>
    <dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">{[[tr('Assigned to','المسؤول'),name(row.assigned_to)],[tr('Created by','أنشأه'),name(d.created_by_member_id??d.created_by??d.reported_by)],[tr('Created','تاريخ الإنشاء'),formattedDate(row.created_at,ar)],[tr('Last updated','آخر تحديث'),formattedDate(row.updated_at,ar)],[tr('Next action','الخطوة القادمة'),row.next_action??'—'],[tr('Follow-up','المتابعة'),`${row.due_date??'—'} ${row.due_time??''}`]].map(([label,value])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>)}</dl>
    <ContactButtons row={row} ar={ar}/>
    {row.location_id?<p className="text-sm">{tr('Location','الموقع')}: {context.staff?<Link className="text-sky-800 underline" href={crmHref('location',row.location_id)}>{row.location_name??tr('Open location','فتح الموقع')}</Link>:row.location_name}</p>:null}
    {section==='location'?<div className="grid gap-3 text-sm sm:grid-cols-2"><div><strong>{tr('Address','العنوان')}</strong><p>{d.address||tr('Not recorded','غير مسجّل')}</p></div><div><strong>{tr('Main contact','المسؤول في الموقع')}</strong><p>{d.contact_name||tr('Not recorded','غير مسجّل')} · {d.contact_phone??''}</p></div><div><strong>{tr('Relationship owner','مسؤول العلاقة')}</strong><p>{name(d.relationship?.assigned_to)}</p></div><div><strong>{tr('Last contact','آخر تواصل')}</strong><p>{formattedDate(d.relationship?.last_contact_at,ar)}</p></div>{d.rent_amount!==undefined?<div><strong>{tr('Recorded rent','الإيجار المسجّل')}</strong><p>{Number(d.rent_amount)>0?money(d.rent_amount):tr('Not configured','غير مضبوط')}</p><p className="text-xs text-slate-500">{tr('Terms only. Upcoming obligations and actual payments are shown separately.','شروط الاتفاق فقط. تظهر الالتزامات والدفعات الفعلية منفصلة.')}</p></div>:null}<div><strong>{tr('Payment frequency','تكرار الدفع')}</strong><p>{d.relationship?.payment_frequency??tr('Not configured','غير مضبوط')}</p></div><div><strong>{tr('Next rent due','موعد الإيجار القادم')}</strong><p>{d.relationship?.payment_recurring?(d.relationship?.next_payment_due_date??tr('Not configured','غير مضبوط')):tr('Recurring rent not enabled','الإيجار الدوري غير مفعّل')}</p></div><div><strong>{tr('Recurring rent','الإيجار الدوري')}</strong><p>{d.relationship?.payment_recurring?tr('Enabled','مفعّل'):tr('Not enabled','غير مفعّل')}</p></div>{d.relationship?.notes?<p className="whitespace-pre-wrap sm:col-span-2">{d.relationship.notes}</p>:null}</div>:null}
    {section==='lead'&&d.converted_location_id?<Link className="btn-secondary" href={crmHref('location',d.converted_location_id)}>{tr('Open connected Snacky location','فتح موقع سناكي المرتبط')}</Link>:null}
    {d.description||d.notes?<p className="whitespace-pre-wrap break-words text-sm leading-6">{d.description??d.notes}</p>:null}
    {section==='issue'?<><p className="text-sm">{tr('Amount involved','المبلغ')}: {money(d.amount_involved_lyd)} · {tr('Product / lane','رقم المنتج / المسار')}: {d.lane_number??'—'}</p>{d.waiting_on?<p className="rounded-lg bg-amber-50 p-3 text-sm">{tr('Waiting for','بانتظار')}: {d.waiting_on}</p>:null}{d.resolution?<div className="rounded-lg bg-emerald-50 p-4 text-sm"><strong>{tr('Resolution','الحل')}</strong><p className="mt-2 whitespace-pre-wrap">{d.resolution}</p><p>{tr('Refund reported','المبلغ المسترد المسجّل')}: {money(d.refund_amount_lyd)}</p><p>{name(d.resolved_by)} · {formattedDate(d.resolved_at,ar)}</p></div>:null}</>:null}
    {section==='task'&&taskDispatch?<CrmDispatchTaskPanel task={taskDispatch} userId={profile.id} ar={ar} canAct={row.assigned_to===context.me&&!row.archived} proofImages={taskProofImages}/>:null}
    {section==='obligation'?<div className={`rounded-xl border p-4 text-sm ${d.is_historical?'border-violet-200 bg-violet-50':'border-amber-200'}`}><strong>{money(d.amount_lyd)}</strong><p>{d.status==='paid'?`${tr('Reported paid by','سجّل الدفع')}: ${name(d.paid_by)} · ${d.payment_date??tr('Exact paid date not recorded','تاريخ الدفع الدقيق غير مسجّل')}`:tr('Payment not reported yet','لم يُسجّل الدفع بعد')}</p>{d.is_historical?<><p className="mt-2 font-medium">{tr('Historical backfill — no current action required','سجل تاريخي مضاف للماضي — لا يتطلب إجراء حالياً')}</p>{d.historical_source?<p className="mt-1 text-xs text-slate-600">{tr('Source','المصدر')}: {d.historical_source}</p>:null}</>:<p>{d.finance_verified_at?tr('Matching Finance expense verified','تم التحقق من حركة المصروف المالية المطابقة'):tr('No Finance entry has been verified. A reported payment is not an accounting posting.','لم يتم التحقق من حركة مالية. تسجيل الدفع هنا لا ينشئ قيداً محاسبياً.')}</p>}</div>:null}
    {context.machines?.length?<div className="space-y-2">{context.machines.map((m:any)=><div key={m.id} className="rounded-lg border p-3 text-sm"><strong>{m.name}</strong><p>{m.machine_code} · {m.status} · {m.online_status??tr('Online state unknown','الاتصال غير معروف')}</p><p className="text-xs text-slate-500">{tr('Last status update','آخر تحديث للحالة')}: {formattedDate(m.last_status_at,ar)}</p>{context.manager?<Link className="text-sky-800 underline" href={`/machines/${m.id}`}>{tr('Machine record','سجل الماكينة')}</Link>:null}</div>)}</div>:null}
   </section>
   {section==='location'&&context.manager?<CrmLocationPaymentScheduleForm locationId={row.id} rentAmount={Number(d.rent_amount??0)} agreementType={d.relationship?.agreement_type??'other'} frequency={d.relationship?.payment_frequency??'monthly'} nextDueDate={d.relationship?.next_payment_due_date??''} recurring={Boolean(d.relationship?.payment_recurring)} noticeDays={Number(d.relationship?.payment_notice_days??7)} ar={ar}/>:null}
   {detailEdit&&section!=='obligation'?<details className="surface-card" open={section==='task'}><summary className="cursor-pointer font-semibold">{section==='task'?tr('Update your work / complete task','تحديث عملك / إكمال المهمة'):tr('Edit record','تعديل السجل')}</summary><div className="mt-4"><CrmRecordForm kind={kind} row={row} context={context} userId={profile.id} ar={ar}/></div></details>:null}
   {detailEdit?<details className="surface-card"><summary className="cursor-pointer font-semibold">+ {tr('Log call, visit or note','تسجيل مكالمة أو زيارة أو ملاحظة')}</summary><div className="mt-4"><CrmNoteForm kind={kind} id={row.id} userId={profile.id} ar={ar}/></div></details>:null}
   {detailEdit&&context.staff&&section!=='task'?<details className="surface-card"><summary className="cursor-pointer font-semibold">+ {section==='issue'?tr('Assign operator action / customer follow-up','تعيين إجراء للمشغّل / متابعة العميل'):tr('Schedule follow-up / meeting','جدولة متابعة / موعد')}</summary><div className="mt-4"><CrmFollowupForm kind={kind} id={row.id} context={context} userId={profile.id} ar={ar}/></div></details>:null}
   {section==='lead'&&row.can_edit&&row.status==='accepted'&&!d.converted_location_id?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Convert to Snacky Location','تحويل إلى موقع سناكي')}</h2><CrmForm action="lead.convert" recordId={row.id} userId={profile.id} fields={[{name:'existing_location_id',label:tr('Create or link','إنشاء أو ربط'),type:'select',options:[{value:'',label:tr('Create a new location','إنشاء موقع جديد')},...(context.options.locations??[]).map((l:any)=>({value:l.id,label:l.name}))]}]} submitLabel={tr('Convert accepted lead','تحويل الجهة المقبولة')}/><p className="mt-3 text-xs text-slate-500">{tr('Contacts and original history stay linked. This does not install a machine or turn proposed rent into an expense.','تظل جهات الاتصال والسجلات الأصلية مرتبطة. التحويل لا يركّب ماكينة ولا يحوّل الإيجار المقترح إلى مصروف.')}</p></section>:null}
   {section==='obligation'&&row.can_edit&&d.status==='open'&&!d.is_historical?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Report actual payment','تسجيل الدفع الفعلي')}</h2><CrmForm action="obligation.paid" recordId={row.id} userId={profile.id} fields={[{name:'payment_date',label:tr('Actual paid date','تاريخ الدفع الفعلي'),type:'date',required:true,value:context.today},{name:'payment_method',label:tr('Method','الطريقة'),type:'select',options:crmOptionRows([['cash','Cash','نقداً'],['bank_transfer','Bank transfer','تحويل مصرفي'],['other','Other','أخرى']],ar)}]} submitLabel={tr('Mark reported paid','تسجيل كمدفوع')} stay/><p className="mt-3 text-xs text-slate-500">{tr('Attach the receipt below first. Management verifies the separate Finance record.','أرفق الإيصال أدناه أولاً. تتحقق الإدارة من السجل المالي المنفصل.')}</p></section>:null}
   {section==='obligation'&&context.owner_admin&&d.status==='paid'&&!d.finance_verified_at&&!d.is_historical?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Link matching Finance payment','ربط حركة الدفع المالية المطابقة')}</h2><CrmForm action="obligation.verify" recordId={row.id} userId={profile.id} fields={[{name:'finance_transaction_id',label:tr('Matching recorded Finance payment','الدفعة المالية المسجّلة المطابقة'),type:'select',required:true,options:[{value:'',label:tr('Choose the matching payment','اختر الدفعة المطابقة')},...(context.options.finance_payments??[]).map((f:any)=>({value:f.id,label:`${f.date} · ${money(f.amount)} · ${f.description??''}`}))],hint:tr('Only existing expenses with this location, amount and paid date appear. This does not create a second expense.','تظهر المصروفات الموجودة المطابقة للموقع والمبلغ والتاريخ فقط. لا ينشئ هذا مصروفاً ثانياً.')}]} submitLabel={tr('Verify existing expense','التحقق من المصروف الموجود')} stay/><Link className="mt-3 block text-sm underline" href="/finance/transactions">{tr('Open Finance transactions','فتح الحركات المالية')}</Link></section>:null}
   {section==='obligation'&&context.manager&&d.frequency!=='once'&&!d.is_historical?<section className="surface-card"><CrmForm action="obligation.next" recordId={row.id} userId={profile.id} fields={[]} submitLabel={tr('Create next recurring obligation','إنشاء الالتزام الدوري التالي')}/></section>:null}
   {context.tasks?.length?<section className="surface-card"><h2 className="mb-4 font-semibold">{tr('Linked work — including completed','العمل المرتبط — بما فيه المكتمل')}</h2><div className="space-y-3">{context.tasks.map((t:any)=><div key={t.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><Link className="font-medium underline" href={crmHref('task',t.id)}>{t.title}</Link><Badge status={t.status} ar={ar}/></div><p className="mt-2 text-xs text-slate-500">{name(t.assigned_to)} · {t.due_date} {t.due_time??''}</p>{t.result?<p className="mt-2 whitespace-pre-wrap text-sm">{t.result}</p>:null}</div>)}</div></section>:null}
   {context.staff&&['lead','location','issue'].includes(section)?<section className="surface-card"><h2 className="font-semibold">{tr('Contacts','جهات الاتصال')}</h2><div className="mt-3 space-y-3">{context.contacts?.map((c:any)=><div className="rounded-xl border p-3" key={c.id}><Link className="font-medium underline" href={crmHref('contact',c.id)}>{c.name}</Link><p className="my-2 text-sm">{c.position} · {c.organization}</p><ContactButtons row={c} ar={ar}/></div>)}</div>{row.can_edit?<details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">+ {tr('Add reusable contact','إضافة جهة اتصال قابلة لإعادة الاستخدام')}</summary><div className="mt-3"><CrmForm action="contact.save" userId={profile.id} hidden={{kind,related_id:row.id}} fields={[{name:'name',label:tr('Name','الاسم'),required:true},{name:'phone',label:tr('Phone','الهاتف'),type:'tel'},{name:'position',label:tr('Position','الصفة')},{name:'email',label:tr('Email','البريد الإلكتروني'),type:'email'},{name:'whatsapp',label:'WhatsApp',type:'tel'}]} submitLabel={tr('Save and link contact','حفظ جهة الاتصال وربطها')} stay/></div></details>:null}</section>:null}
   <section className="surface-card"><h2 className="font-semibold">{tr('Documents & proof','المستندات والإثباتات')}</h2><div className="my-3 space-y-2">{context.documents?.map((doc:any)=><a key={doc.id} className="block break-words text-sm text-sky-800 underline" href={`/api/crm/documents/${doc.id}`} target="_blank" rel="noreferrer">{doc.original_name}</a>)}</div>{row.can_edit?<CrmDocumentUpload kind={kind} recordId={row.id} userId={profile.id}/>:null}</section>
   <section className="surface-card"><h2 className="mb-4 font-semibold">{tr('Activity history','سجل النشاط')}</h2><ol className="space-y-4 border-s border-slate-200 ps-4">{[...(context.activities??[])].sort((a:any,b:any)=>b.occurred_at.localeCompare(a.occurred_at)).map((a:any)=><li key={a.id}><p className="text-xs text-slate-500">{formattedDate(a.occurred_at,ar)} · {a.actor_name??tr('Historical / system entry','سجل تاريخي / نظام')}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{a.summary==='Created'?tr('Record created','تم إنشاء السجل'):a.summary==='Record updated'?tr('Record updated','تم تحديث السجل'):a.summary==='Assignment changed'?tr('Assignment changed','تم تغيير المسؤول'):a.summary}</p>{a.after_data?.result?<p className="mt-2 whitespace-pre-wrap text-sm">{a.after_data.result}</p>:null}</li>)}</ol>{!context.activities?.length?<p className="text-sm text-slate-500">{tr('No recorded activity yet.','لا يوجد نشاط مسجّل بعد.')}</p>:null}<div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span>{tr('Activity entries','أنشطة السجل')}: {context.history_total??0}</span>{Number(context.history_offset)>0?<Link className="btn-secondary" href={`${crmHref(kind,row.id)}?history_offset=${Math.max(0,Number(context.history_offset)-40)}`}>{tr('Newer activity','أنشطة أحدث')}</Link>:null}{Number(context.history_offset??0)+40<Number(context.history_total??0)?<Link className="btn-secondary" href={`${crmHref(kind,row.id)}?history_offset=${Number(context.history_offset??0)+40}`}>{tr('Older activity','أنشطة أقدم')}</Link>:null}</div></section>
   {context.related?.length?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Related records','السجلات المرتبطة')}</h2><div className="space-y-2">{context.related.map((r:any)=><Link className="block text-sm underline" href={crmHref(r.kind,r.id)} key={`${r.kind}:${r.id}`}>{crmNames[r.kind as CrmSection]?.[ar?1:0]} · {r.title} · {crmStatus(r.status,ar)}</Link>)}</div></section>:null}
   {section==='lead'&&context.owner_admin?<details className="surface-card"><summary className="cursor-pointer font-semibold">{tr('Successful-location bonus — management','مكافأة الموقع الناجح — الإدارة')}</summary><div className="mt-4"><CrmForm action="bonus.save" recordId={row.id} userId={profile.id} fields={[{name:'eligible',label:tr('Eligible','مستحق للمكافأة'),type:'checkbox',value:String(context.bonus?.eligible??false)},{name:'amount_lyd',label:tr('Amount (optional, LYD)','المبلغ (اختياري، د.ل)'),type:'number',min:0,value:String(context.bonus?.amount_lyd??'')},{name:'status',label:tr('Status','الحالة'),type:'select',value:context.bonus?.status??'pending',options:crmOptionRows([['pending','Pending','بانتظار الموافقة'],['approved','Approved','معتمدة'],['paid','Paid','مدفوعة']],ar)},{name:'notes',label:tr('Approval / payment reference','مرجع الموافقة أو الدفع'),type:'textarea',value:context.bonus?.notes??''}]} submitLabel={tr('Save bonus tracking','حفظ متابعة المكافأة')} stay/><p className="mt-3 text-xs text-slate-500">{tr('Tracking only. No salary calculation or Finance payout is created.','للمتابعة فقط. لا يتم احتساب راتب أو إنشاء دفعة مالية.')}</p></div></details>:null}
   {context.manager&&(['lead','issue','task','contact'].includes(section)||(section==='obligation'&&d.status==='open'))?<details className="surface-card"><summary className="cursor-pointer text-sm font-semibold text-amber-900">{row.archived?tr('Restore record','استعادة السجل'):tr('Archive / cancel without deleting history','أرشفة أو إلغاء دون حذف السجل')}</summary><div className="mt-3"><CrmForm action="record.archive" recordId={row.id} userId={profile.id} hidden={{kind,restore:String(Boolean(row.archived))}} fields={[{name:'reason',label:tr('Reason','السبب'),required:true}]} submitLabel={row.archived?tr('Restore','استعادة'):tr('Archive / cancel','أرشفة / إلغاء')} stay/></div></details>:null}
  </>:null}
 </div>;
}
