/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {getAuthenticatedSupabaseServerClient,getCurrentProfile} from '@/lib/auth';
import {hasAnyRole} from '@/lib/authz';
import {getServerI18n} from '@/lib/i18n/server';
import {ErrorState,PageHeader} from '@/components/ui';
import {CrmLeadSummary} from '@/components/CrmLeadSummary';
import {CrmLeadQuickPanel} from '@/components/CrmLeadQuickPanel';
import {CrmForm} from '@/components/CrmForm';
import {CrmDocumentUpload,CrmRefresh} from '@/components/CrmClientTools';
import {CrmRecordForm,CrmFollowupForm,CrmNoteForm} from '@/components/CrmRecordForms';
import {crmHref,crmStatus,crmContactLink,crmOptionRows,uuidPattern} from '@/lib/crm-workspace';
import type {CrmSearchParams} from '@/components/CrmWorkspace';
/** Lead-only layout. Other CRM pages retain their existing rendering and writers. */
export async function LeadCrmWorkspace({id,searchParams={}}:{id:string;searchParams?:CrmSearchParams}){
 const profile=await getCurrentProfile();if(!profile||profile.active_status!=='active'||!hasAnyRole(profile,['owner','admin','supervisor','crm']))redirect('/unauthorized');
 const {locale}=await getServerI18n(),ar=locale==='ar',tr=(en:string,arabic:string)=>ar?arabic:en;
 const value=(key:string)=>typeof searchParams[key]==='string'?String(searchParams[key]):'';
 const date=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat(ar?'ar-LY':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Tripoli'}).format(d);};
 let context:any;
 try{
  if(!uuidPattern.test(id))throw Error('invalid_id');const db=await getAuthenticatedSupabaseServerClient();if(!db)throw Error('session');
  const result=await db.rpc('snacky_crm_workspace_v1',{p_section:'lead',p_id:id,p_filters:value('history_offset')?{history_offset:value('history_offset')}:{}});
  if(result.error||!result.data?.record||result.data.record.id!==id)throw result.error??Error('record');context=result.data;
 }catch{return <ErrorState title={tr('Lead unavailable','الجهة غير متاحة')} body={tr('Could not verify this record or your access. No changes were made.','تعذر التحقق من السجل أو صلاحياتك. لم يتم تغيير أي بيانات.')}/>;}
 const row=context.record,d=row.data??{},canEdit=Boolean(row.can_edit&&!row.archived),name=(m:string)=>context.directory?.find((p:any)=>p.id===m)?.name??tr('Unassigned','غير مسند');
 return <div className="min-w-0 space-y-5" dir={ar?'rtl':'ltr'} data-lead-detail>
  <CrmRefresh/>
  <PageHeader title={row.title} subtitle={tr('The place, the next action and its full history.','الجهة والخطوة القادمة وسجلها الكامل.')} action={<Link className="btn-secondary" href="/locations-pipeline">{tr('Back to list','العودة للقائمة')}</Link>}/>
  {row.archived||row.is_practice?<p className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">{row.archived?tr('Archived — history preserved','مؤرشف — السجل محفوظ'):tr('Practice record — not real work','سجل تدريبي — ليس عملاً فعلياً')}</p>:null}
  <CrmLeadSummary id={id} status={row.status} assignedName={name(row.assigned_to)} nextAction={row.next_action} dueDate={row.due_date} dueTime={row.due_time} canEdit={canEdit} manager={context.manager} data={d} ar={ar}/>
  {canEdit?<>
   <details className="surface-card" id="lead-edit" open={value('edit')==='1'}><summary className="cursor-pointer font-semibold">{tr('Edit record','تعديل السجل')}</summary><div className="mt-4"><CrmRecordForm kind="lead" row={row} context={context} userId={profile.id} ar={ar}/></div></details>
   <details className="surface-card"><summary className="cursor-pointer font-semibold">+ {tr('Log call, visit or note','تسجيل مكالمة أو زيارة أو ملاحظة')}</summary><div className="mt-4"><CrmNoteForm kind="lead" id={id} userId={profile.id} ar={ar}/></div></details>
   {!['machine_placed','rejected'].includes(row.status)?<details className="surface-card"><summary className="cursor-pointer font-semibold">+ {tr('Schedule follow-up / meeting','جدولة متابعة / موعد')}</summary><div className="mt-4"><CrmFollowupForm kind="lead" id={id} context={context} userId={profile.id} ar={ar}/></div></details>:null}
  </>:null}
  {canEdit&&row.status==='accepted'&&!d.converted_location_id?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Convert to Snacky Location','تحويل إلى موقع سناكي')}</h2><CrmForm action="lead.convert" recordId={id} userId={profile.id} fields={[{name:'existing_location_id',label:tr('Create or link','إنشاء أو ربط'),type:'select',options:[{value:'',label:tr('Create a new location','إنشاء موقع جديد')},...(context.options.locations??[]).map((l:any)=>({value:l.id,label:l.name}))]}]} submitLabel={tr('Convert accepted lead','تحويل الجهة المقبولة')}/><p className="mt-3 text-xs text-slate-500">{tr('Contacts and original history stay linked. Linking a location does not install a machine or create a rent expense.','تبقى جهات الاتصال والسجلات الأصلية مرتبطة. ربط الموقع لا يركّب ماكينة ولا ينشئ مصروف إيجار.')}</p></section>:null}
  <section className="surface-card" id="lead-history"><h2 className="mb-4 font-semibold">{tr('Activity history','سجل النشاط')}</h2><ol className="space-y-4 border-s border-slate-200 ps-4">{[...(context.activities??[])].sort((a:any,b:any)=>b.occurred_at.localeCompare(a.occurred_at)).map((a:any)=><li key={a.id}><p className="text-xs text-slate-500">{date(a.occurred_at)} · {a.actor_name??tr('Historical / system entry','سجل تاريخي / نظام')}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{a.summary==='Created'?tr('Record created','تم إنشاء السجل'):a.summary==='Record updated'?tr('Record updated','تم تحديث السجل'):a.summary==='Assignment changed'?tr('Assignment changed','تم تغيير المسؤول'):a.summary}</p>{a.after_data?.result?<p className="mt-2 whitespace-pre-wrap text-sm">{a.after_data.result}</p>:null}</li>)}</ol>{!context.activities?.length?<p className="text-sm text-slate-500">{tr('No recorded activity yet.','لا يوجد نشاط مسجّل بعد.')}</p>:null}<div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span>{tr('Activity entries','أنشطة السجل')}: {context.history_total??0}</span>{Number(context.history_offset)>0?<Link className="btn-secondary" href={`${crmHref('lead',id)}?history_offset=${Math.max(0,Number(context.history_offset)-40)}#lead-history`}>{tr('Newer activity','أنشطة أحدث')}</Link>:null}{Number(context.history_offset??0)+40<Number(context.history_total??0)?<Link className="btn-secondary" href={`${crmHref('lead',id)}?history_offset=${Number(context.history_offset??0)+40}#lead-history`}>{tr('Older activity','أنشطة أقدم')}</Link>:null}</div></section>
  {context.tasks?.length?<section className="surface-card"><h2 className="mb-4 font-semibold">{tr('Linked work — including completed','العمل المرتبط — بما فيه المكتمل')}</h2><div className="space-y-3">{context.tasks.map((t:any)=><div key={t.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><Link className="font-medium underline" href={crmHref('task',t.id)}>{t.title}</Link><span className="text-sm">{crmStatus(t.status,ar)}</span></div><p className="mt-2 text-xs text-slate-500">{name(t.assigned_to)} · {t.due_date} {t.due_time??''}</p>{t.result?<p className="mt-2 whitespace-pre-wrap text-sm">{t.result}</p>:null}</div>)}</div></section>:null}
  <section className="surface-card" id="lead-files"><h2 className="font-semibold">{tr('Documents & proof','المستندات والإثباتات')}</h2><div className="my-3 space-y-2">{context.documents?.map((doc:any)=><a key={doc.id} className="block break-words text-sm text-sky-800 underline" href={`/api/crm/documents/${doc.id}`} target="_blank" rel="noreferrer">{doc.original_name}</a>)}</div>{canEdit?<CrmDocumentUpload kind="lead" recordId={id} userId={profile.id}/>:null}</section>
  <section className="surface-card"><h2 className="font-semibold">{tr('Contacts','جهات الاتصال')}</h2><div className="mt-3 space-y-3">{context.contacts?.map((c:any)=><div className="rounded-xl border p-3" key={c.id}><Link className="font-medium underline" href={crmHref('contact',c.id)}>{c.name}</Link><p className="my-2 text-sm">{c.position} · {c.organization}</p><div className="flex flex-wrap gap-3">{(['phone','whatsapp','email'] as const).map(k=>{const url=crmContactLink(k,c[k]);return url?<a className="text-sm text-sky-800 underline" key={k} href={url} target={k==='whatsapp'?'_blank':undefined} rel="noopener noreferrer">{k==='phone'?tr('Call','اتصال'):k==='email'?tr('Email','البريد الإلكتروني'):'WhatsApp'}</a>:null;})}</div></div>)}</div>{canEdit?<details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">+ {tr('Add reusable contact','إضافة جهة اتصال قابلة لإعادة الاستخدام')}</summary><div className="mt-3"><CrmForm action="contact.save" userId={profile.id} hidden={{kind:'lead',related_id:id}} fields={[{name:'name',label:tr('Name','الاسم'),required:true},{name:'phone',label:tr('Phone','الهاتف'),type:'tel'},{name:'position',label:tr('Position','الصفة')},{name:'email',label:tr('Email','البريد الإلكتروني'),type:'email'},{name:'whatsapp',label:'WhatsApp',type:'tel'}]} submitLabel={tr('Save and link contact','حفظ جهة الاتصال وربطها')} stay/></div></details>:null}</section>
  {context.related?.length?<section className="surface-card"><h2 className="mb-3 font-semibold">{tr('Related records','السجلات المرتبطة')}</h2>{context.related.map((r:any)=><Link className="mb-2 block text-sm underline" href={crmHref(r.kind,r.id)} key={`${r.kind}:${r.id}`}>{r.title} · {crmStatus(r.status,ar)}</Link>)}</section>:null}
  {context.owner_admin?<details className="surface-card"><summary className="cursor-pointer font-semibold">{tr('Successful-location bonus — management','مكافأة الموقع الناجح — الإدارة')}</summary><div className="mt-4"><CrmForm action="bonus.save" recordId={id} userId={profile.id} fields={[{name:'eligible',label:tr('Eligible','مستحق للمكافأة'),type:'checkbox',value:String(context.bonus?.eligible??false)},{name:'amount_lyd',label:tr('Amount (optional, LYD)','المبلغ (اختياري، د.ل)'),type:'number',min:0,value:String(context.bonus?.amount_lyd??'')},{name:'status',label:tr('Status','الحالة'),type:'select',value:context.bonus?.status??'pending',options:crmOptionRows([['pending','Pending','بانتظار الموافقة'],['approved','Approved','معتمدة'],['paid','Paid','مدفوعة']],ar)},{name:'notes',label:tr('Approval / payment reference','مرجع الموافقة أو الدفع'),type:'textarea',value:context.bonus?.notes??''}]} submitLabel={tr('Save bonus tracking','حفظ متابعة المكافأة')} stay/><p className="mt-3 text-xs text-slate-500">{tr('Tracking only. No salary calculation or Finance payout is created.','للمتابعة فقط. لا يتم احتساب راتب أو إنشاء دفعة مالية.')}</p></div></details>:null}
  {context.manager?<details className="surface-card"><summary className="cursor-pointer text-sm font-semibold text-amber-900">{row.archived?tr('Restore record','استعادة السجل'):tr('Archive / cancel without deleting history','أرشفة أو إلغاء دون حذف السجل')}</summary><div className="mt-3"><CrmForm action="record.archive" recordId={id} userId={profile.id} hidden={{kind:'lead',restore:String(Boolean(row.archived))}} fields={[{name:'reason',label:tr('Reason','السبب'),required:true}]} submitLabel={row.archived?tr('Restore','استعادة'):tr('Archive / cancel','أرشفة / إلغاء')} stay/></div></details>:null}
  <p className="text-xs text-slate-500">{tr('Created','تاريخ الإنشاء')}: {date(row.created_at)} · {tr('Last updated','آخر تحديث')}: {date(row.updated_at)}</p>
  {value('quick')===id?<CrmLeadQuickPanel id={id} initialMode={value('quick_action')} ar={ar} returnHref={crmHref('lead',id)}/>:null}
 </div>;
}
