import { notFound, redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { AppShell } from "@/components/AppShell";
import { FormField, FormPageLayout, FormSection, PageHeader, PrimaryButton, SecondaryButton } from "@/components/ui";
import { getSupabaseServerClient } from "@/lib/supabase-server";

async function updateProduct(fd: FormData){"use server"; const s=getSupabaseServerClient(); if(!s) return; const id=String(fd.get('id')); const p={sku:String(fd.get("sku")||"").trim(),barcode:String(fd.get("barcode")||"")||null,name:String(fd.get("name")||"").trim(),category:String(fd.get("category")||"snack"),brand:String(fd.get("brand")||"")||null,supplier_id:String(fd.get("supplier_id")||"")||null,cost_price:Number(fd.get("cost_price")||0),selling_price:Number(fd.get("selling_price")||0),case_quantity:Number(fd.get("case_quantity")||1),active:String(fd.get("active")||"true")==="true"}; await s.from('products').update(p).eq('id',id); revalidatePath('/products'); redirect('/products');}

export default async function EditProductPage({ params }: { params: Promise<{ id: string }> }) {const {id}=await params; const s=getSupabaseServerClient(); if(!s) notFound(); const [{data:product},{data:suppliers}] = await Promise.all([s.from('products').select('*').eq('id',id).single(), s.from('suppliers').select('id,name').order('name')]); if(!product) notFound();
return <AppShell><FormPageLayout><PageHeader title="Edit product" subtitle="Update product profile and pricing."/><form action={updateProduct} className="space-y-5"><input type="hidden" name="id" value={id}/><FormSection title="Product details"><div className="grid gap-4 md:grid-cols-2"><FormField label="SKU" required><input required name="sku" defaultValue={product.sku} className="field-input"/></FormField><FormField label="Barcode"><input name="barcode" defaultValue={product.barcode||""} className="field-input"/></FormField><FormField label="Product Name" required><input required name="name" defaultValue={product.name} className="field-input"/></FormField><FormField label="Category" required><select name="category" defaultValue={product.category} className="field-input"><option>drink</option><option>snack</option><option>chocolate</option><option>biscuit</option><option>coffee</option><option>other</option></select></FormField><FormField label="Brand"><input name="brand" defaultValue={product.brand||""} className="field-input"/></FormField><FormField label="Supplier"><select name="supplier_id" defaultValue={product.supplier_id||""} className="field-input"><option value="">Select supplier</option>{suppliers?.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></FormField></div></FormSection><div className="flex gap-3"><PrimaryButton>Save changes</PrimaryButton><SecondaryButton href="/products">Cancel</SecondaryButton></div></form></FormPageLayout></AppShell>;}
