"""One-time, fail-closed source integration on the feature branch. No database/network access."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
def change(path,old,new):
 p=root/path;s=p.read_text(encoding='utf-8-sig')
 if old not in s: raise RuntimeError('Integration anchor missing: '+path+' '+old[:80])
 p.write_text(s.replace(old,new),encoding='utf-8')
change('src/lib/authz.ts','if (matchesPrefix(pathname, ["/buying-lists"])) return hasAnyRole(user, ["owner", "admin", "supervisor", "crm", "operator", "warehouse", "purchasing", "finance"]);','if (matchesPrefix(pathname, ["/buying-lists"])) return hasAnyRole(user, ["owner", "admin", "supervisor", "operator", "warehouse", "purchasing", "finance"]);')
change('src/lib/authz.ts','  if (matchesPrefix(pathname, ["/my-work/team"]))','  if (matchesPrefix(pathname, ["/my-work/notes"])) return hasAnyRole(user, ["owner", "admin", "crm"]);\n  if (matchesPrefix(pathname, ["/my-work/team"]))')
change('src/lib/buying-lists.ts',"export const buyingRoles = ['owner','admin','supervisor','crm','operator','warehouse','purchasing','finance']", "export const buyingRoles = ['owner','admin','supervisor','operator','warehouse','purchasing','finance']")
change('src/components/Sidebar.tsx','["crm", "operator", "finance"]) && !hasAnyRole(context, ["warehouse", "purchasing"])) work.push(buyingListsItem);','["operator", "finance"]) && !hasAnyRole(context, ["warehouse", "purchasing"])) work.push(buyingListsItem);')
change('src/components/Sidebar.tsx','const companyItem: NavItem =','const managementNotesItem: NavItem = { label: { en: "Management notes", ar: "ملاحظات الإدارة" }, href: "/my-work/notes", icon: ClipboardList };\n\nconst companyItem: NavItem =')
change('src/components/Sidebar.tsx','  if (hasPermission(context, "machines.view")) work.push(machinesItem);','  if (hasAnyRole(context, ["owner", "admin", "crm"])) work.push(managementNotesItem);\n  if (hasPermission(context, "machines.view")) work.push(machinesItem);')
change('src/components/Sidebar.tsx','{ title: sectionTitles.system, items: [adminItem] }','{ title: sectionTitles.system, items: [adminItem, managementNotesItem] }')
change('src/components/module-tabs-config.ts','const crmTabs: ModuleTab[] = [','const crmTabs: ModuleTab[] = [\n  { label: "Management notes", href: "/my-work/notes", labelAr: "ملاحظات الإدارة", exact: true },')
change('src/app/my-work/page.tsx',"export const dynamic='force-dynamic';","import {CrmNotesSummary} from '@/components/CrmNotesSummary';\nexport const dynamic='force-dynamic';")
change('src/app/my-work/page.tsx','return <><CrmLeadFocusOverview/>','return <><CrmNotesSummary/><CrmLeadFocusOverview/>')
change('src/app/admin/operations/page.tsx',"export const dynamic='force-dynamic';","import {CrmNotesSummary} from '@/components/CrmNotesSummary';\nexport const dynamic='force-dynamic';")
change('src/app/admin/operations/page.tsx','return <OwnerOperationsWorkspace initial={await loadOperations(context.read)}/>;','return <><CrmNotesSummary/><OwnerOperationsWorkspace initial={await loadOperations(context.read)}/></>;')
change('src/lib/crm-lead-list.ts',"'offset','group','focus']", "'offset','group','focus','label']")
change('src/lib/crm-lead-list.ts','export type LeadRow={','export type LeadRow={\n labels?:import(\'./crm-collaboration\').CrmLabel[];')
change('src/lib/crm-lead-list.ts','export type LeadWorkspaceData={','export type LeadWorkspaceData={\n label_options?:import(\'./crm-collaboration\').CrmLabel[];')
change('src/components/CrmLeadTable.tsx',"import Link from 'next/link';","import Link from 'next/link';\nimport {CrmLeadLabels} from '@/components/CrmLeadLabels';")
change('src/components/CrmLeadTable.tsx','function LeadName({row,ar}:{row:LeadRow;ar:boolean})','function LeadName({row,ar,labelsEnabled=false}:{row:LeadRow;ar:boolean;labelsEnabled?:boolean})')
change('src/components/CrmLeadTable.tsx','<Flags row={row} ar={ar}/></div>','<Flags row={row} ar={ar}/></div>{labelsEnabled?<CrmLeadLabels leadId={row.id} labels={row.labels??[]} ar={ar}/>:null}')
change('src/components/CrmLeadTable.tsx','export function CrmLeadTable({rows,ar,selection}:{rows:LeadRow[];ar:boolean;selection?', 'export function CrmLeadTable({rows,ar,selection,labelsEnabled=false}:{rows:LeadRow[];ar:boolean;labelsEnabled?:boolean;selection?')
change('src/components/CrmLeadTable.tsx','<LeadName row={row} ar={ar}/>','<LeadName row={row} ar={ar} labelsEnabled={labelsEnabled}/>')
change('src/components/CrmLeadFocusList.tsx','assignees,manager}:{rows:LeadRow[];','assignees,manager,labelsEnabled=false}:{labelsEnabled?:boolean;rows:LeadRow[];')
change('src/components/CrmLeadFocusList.tsx','<CrmLeadTable rows={rows} ar={ar} selection=', '<CrmLeadTable rows={rows} ar={ar} labelsEnabled={labelsEnabled} selection=')
change('src/components/CrmLeadsWorkspace.tsx',"import {CrmLeadTable} from '@/components/CrmLeadTable';","import {CrmLeadTable} from '@/components/CrmLeadTable';\nimport {CrmLeadLabels} from '@/components/CrmLeadLabels';")
change('src/components/CrmLeadsWorkspace.tsx',' const currentOwner='," const labelsEnabled=hasAnyRole(profile,['owner','admin','crm']);\n const currentOwner=")
change('src/components/CrmLeadsWorkspace.tsx','   <div className={styles.toolbar}>','   <div className={styles.toolbar}>\n    {labelsEnabled?<label>{tr(\'Label\',\'التصنيف\')}<select name="label" defaultValue={filters.label??\'\'}><option value="">{tr(\'All labels\',\'كل التصنيفات\')}</option>{(context.label_options??[]).map(l=><option key={l.id} value={l.id}>{l.name}{context.manager?\' · \'+l.owner_name:\'\'}</option>)}</select></label>:null}')
change('src/components/CrmLeadsWorkspace.tsx','  <div className={styles.listSummary}>','  {labelsEnabled?<CrmLeadLabels ar={ar}/>:null}\n  <div className={styles.listSummary}>')
change('src/components/CrmLeadsWorkspace.tsx',' manager={context.manager} assignees=', ' manager={context.manager} labelsEnabled={labelsEnabled} assignees=')
change('src/components/CrmLeadsWorkspace.tsx','<CrmLeadTable rows={context.rows} ar={ar}/>','<CrmLeadTable rows={context.rows} ar={ar} labelsEnabled={labelsEnabled}/>')
change('src/components/CrmLeads.module.css','grid-template-columns:minmax(200px,2fr) minmax(135px,1fr) minmax(155px,1fr) auto;','grid-template-columns:minmax(130px,1fr) minmax(180px,2fr) minmax(130px,1fr) minmax(145px,1fr) auto;')
change('scripts/test-shared-buying.mjs',"for(const role of ['operator','crm'])", "for(const role of ['operator'])")
change('scripts/test-shared-buying.mjs',"for(const role of ['investor','viewer'])", "for(const role of ['crm','investor','viewer'])")
# Keep immutable notes/create inputs and pending retry scoped to their actual form.
change('src/components/CrmManagementNotes.tsx',"useCrmCollaborationCommand(userId,'new-note',ar)","useCrmCollaborationCommand(userId,'new-note:'+(leadId??'general'),ar)")
change('src/components/CrmManagementNotes.tsx','onClick={()=>{setFilter(value);','onClick={()=>{if(filter===value)return;setFilter(value);')
# Avoid ambiguous unqualified identifiers inside the transactional function.
p=root/'supabase/migrations/20260927123856_crm_notes_labels_v1.sql';s=p.read_text()
for old,new in [('rid uuid;id uuid;','rid uuid;v_id uuid;'),("id:=(p_command->>'id')","v_id:=(p_command->>'id')"),('or id is null','or v_id is null'),('values(id,actor,','values(v_id,actor,'),('where notes.id=id','where notes.id=v_id'),('where labels.id=id','where labels.id=v_id'),('lead:=id;','lead:=v_id;'),("'id',id,'action'","'id',v_id,'action'"),('values(actor,act,id,','values(actor,act,v_id,')]:
 if old not in s: raise RuntimeError('SQL identifier anchor missing '+old)
 s=s.replace(old,new)
p.write_text(s)
print('CRM integration applied; no production records accessed.')
