-- Additive Company hub. Filename generated by Supabase CLI 2.117.0 in isolated CI.
-- No employee identities, approved policies, uploaded documents or operational/financial writes.
create schema if not exists company_private;
revoke all on schema company_private from public,anon;
grant usage on schema company_private to authenticated;
create table company_private.items (
 id uuid primary key, draft jsonb not null, revision integer not null default 1 check(revision>0),
 current_version integer not null default 0 check(current_version>=0), archived boolean not null default false,
 created_by uuid not null references auth.users(id) on delete restrict,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table company_private.versions (
 item_id uuid not null references company_private.items(id) on delete restrict,
 version integer not null check(version>0), data jsonb not null,
 published_by uuid not null references auth.users(id) on delete restrict,
 published_at timestamptz not null default now(), primary key(item_id,version)
);
create table company_private.receipts (
 item_id uuid not null, version integer not null, user_id uuid not null references auth.users(id) on delete restrict,
 read_at timestamptz, ack_at timestamptz, primary key(item_id,version,user_id),
 foreign key(item_id,version) references company_private.versions(item_id,version) on delete restrict
);
create table company_private.files (
 id uuid primary key, object_path text not null unique, original_name text not null,
 mime_type text not null, digest text not null, size_bytes bigint not null check(size_bytes between 1 and 4000000),
 created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now()
);
create table company_private.commands (
 id uuid primary key, actor uuid not null references auth.users(id) on delete restrict,
 request jsonb not null, response jsonb not null, created_at timestamptz not null default now()
);
do $$declare t text;begin
 foreach t in array array['items','versions','receipts','files','commands'] loop
  execute format('alter table company_private.%I enable row level security',t);
  execute format('revoke all on company_private.%I from public,anon,authenticated',t);
 end loop;
end $$;
create index company_versions_file on company_private.versions((data->>'file_id'));
create index company_receipts_user on company_private.receipts(user_id,item_id,version);
create function company_private.staff() returns boolean language sql stable security definer set search_path='' as $$
 select auth.uid() is not null and public.snacky_current_team_member_id() is not null
 and public.snacky_current_profile_has_any_role(array['owner','admin','supervisor','crm','operator','warehouse','purchasing','finance']);
$$;
create function company_private.manager() returns boolean language sql stable security definer set search_path='' as $$
 select company_private.staff() and public.snacky_current_profile_has_any_role(array['owner','admin']);
$$;
create function company_private.audience(d jsonb) returns boolean language sql stable security definer set search_path='' as $$
 select company_private.staff() and public.snacky_current_profile_has_any_role(array(select jsonb_array_elements_text(d->'audience')));
$$;
create function company_private.visible(i uuid,v integer default null) returns boolean language sql stable security definer set search_path='' as $$
 select company_private.staff() and exists(
  select 1 from company_private.items x left join company_private.versions current on current.item_id=x.id and current.version=x.current_version
  where x.id=i and (company_private.manager() or (not x.archived and company_private.audience(current.data)
   and (v is null or exists(select 1 from company_private.versions old where old.item_id=i and old.version=v and company_private.audience(old.data))))));
$$;
create function company_private.file_access(p_name text) returns boolean language sql stable security definer set search_path='' as $$
 select company_private.staff() and (company_private.manager() or exists(
  select 1 from company_private.files f join company_private.versions v on v.data->>'file_id'=f.id::text
  where f.object_path=p_name and company_private.visible(v.item_id,v.version)));
$$;
create function public.snacky_company_file_access(p_name text) returns boolean language sql stable security invoker set search_path='' as $$select company_private.file_access(p_name);$$;
create function company_private.validate(d jsonb,publish boolean default false) returns void language plpgsql security definer set search_path='' as $$
declare k text; txt text; owner uuid;
begin
 if d is null or jsonb_typeof(d)<>'object' then raise exception 'Invalid content' using errcode='22023';end if;
 foreach k in array array['title_en','title_ar','summary_en','summary_ar','body_en','body_ar','owner_id','review_date','source_url','file_id','work_path','section'] loop
  if jsonb_typeof(d->k) is distinct from 'string' or length(d->>k)>(case when k like 'body_%' then 20000 when k like 'summary_%' then 600 when k like 'title_%' then 160 else 2048 end) then raise exception 'Invalid text field' using errcode='22023';end if;
 end loop;
 if trim(d->>'title_en')='' and trim(d->>'title_ar')='' then raise exception 'A title is required' using errcode='22023';end if;
 if d->>'section' not in ('start','guides','documents','people') then raise exception 'Invalid section' using errcode='22023';end if;
 if jsonb_typeof(d->'audience') is distinct from 'array' then raise exception 'Invalid audience' using errcode='22023';end if;
 if jsonb_array_length(d->'audience') not between 1 and 8 or exists(select 1 from jsonb_array_elements_text(d->'audience') r where r not in ('owner','admin','supervisor','crm','operator','warehouse','purchasing','finance')) then raise exception 'Invalid audience' using errcode='22023';end if;
 foreach k in array array['notify','requires_ack','external_shareable'] loop
  if jsonb_typeof(d->k) is distinct from 'boolean' then raise exception 'Invalid publication option' using errcode='22023';end if;
 end loop;
 if nullif(d->>'owner_id','') is not null then
  owner:=(d->>'owner_id')::uuid;
  if not exists(select 1 from public.team_members t where t.id=owner and t.active_status='active' and t.active is not false) then raise exception 'Choose an active content owner' using errcode='22023';end if;
 end if;
 if nullif(d->>'review_date','') is not null then
  if d->>'review_date' !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'Invalid review date' using errcode='22023';end if;
  perform (d->>'review_date')::date;
 end if;
 txt:=d->>'source_url';
 if txt<>'' and (txt!~'^https://(drive\.google\.com|docs\.google\.com)/' or txt~'[[:cntrl:]]') then raise exception 'Use a Google Drive or Docs HTTPS link' using errcode='22023';end if;
 txt:=d->>'file_id';
 if txt<>'' and not exists(select 1 from company_private.files f where f.id=txt::uuid) then raise exception 'File not registered' using errcode='22023';end if;
 if d->>'work_path' not in ('','/my-work','/my-work/team','/locations-pipeline','/locations-pipeline/new','/issues','/issues/new','/relationships','/relationships/obligations','/follow-ups','/follow-ups/new','/operator/routes','/operator/issues/actions','/inventory','/purchases','/finance','/team') then raise exception 'Invalid work link' using errcode='22023';end if;
 if publish then
  if owner is null or d->>'review_date'='' then raise exception 'Set an active owner and review date before publishing' using errcode='22023';end if;
  if d->>'section'='documents' then
   if d->>'file_id'='' and d->>'source_url'='' then raise exception 'Attach a real file or master link' using errcode='22023';end if;
  elsif trim(d->>'body_en')='' and trim(d->>'body_ar')='' then raise exception 'Write the guide before publishing' using errcode='22023';end if;
 end if;
end $$;
create function company_private.command(p_request uuid,p_action text,p_id uuid,p_revision integer,p_version integer,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare me uuid:=auth.uid(); r company_private.commands%rowtype; x company_private.items%rowtype;
 req jsonb:=jsonb_build_object('action',p_action,'id',p_id,'revision',p_revision,'version',p_version,'payload',p_payload);
 result jsonb; d jsonb; v integer; f company_private.files%rowtype;
begin
 if p_request is null or p_id is null or not company_private.staff() then raise exception 'Not permitted' using errcode='42501';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_request::text,0));
 select * into r from company_private.commands where id=p_request;
 if found then
  if r.actor<>me or r.request<>req then raise exception 'Request identity conflict' using errcode='23505';end if;
  if p_action not in ('read','ack') and not company_private.manager() then raise exception 'Not permitted' using errcode='42501';end if;
  if p_action in ('read','ack') and not company_private.visible(p_id,p_version) then raise exception 'Not permitted' using errcode='42501';end if;
  return r.response;
 end if;
 if p_action='file.register' then
  if not company_private.manager() then raise exception 'Not permitted' using errcode='42501';end if;
  if p_payload->>'digest' !~ '^[0-9a-f]{64}$' or length(p_payload->>'original_name') not between 1 and 200
   or (p_payload->>'size_bytes')::bigint not between 1 and 4000000
   or p_payload->>'mime_type' not in ('application/pdf','image/jpeg','image/png','image/webp','image/svg+xml','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
   or p_payload->>'object_path'<>me::text||'/'||p_id::text||'/'||(p_payload->>'digest') then raise exception 'Invalid upload metadata' using errcode='22023';end if;
  if not exists(select 1 from storage.objects o where o.bucket_id='company-documents' and o.name=p_payload->>'object_path') then raise exception 'Upload not confirmed' using errcode='22023';end if;
  select * into f from company_private.files where id=p_id;
  if found then
   if f.object_path<>p_payload->>'object_path' or f.digest<>p_payload->>'digest' or f.created_by<>me then raise exception 'File identity conflict' using errcode='23505';end if;
  else
   insert into company_private.files(id,object_path,original_name,mime_type,digest,size_bytes,created_by)
    values(p_id,p_payload->>'object_path',p_payload->>'original_name',p_payload->>'mime_type',p_payload->>'digest',(p_payload->>'size_bytes')::bigint,me);
  end if;
  result:=jsonb_build_object('id',p_id,'request_id',p_request);
 elsif p_action in ('read','ack') then
  if p_version is null or not company_private.visible(p_id,p_version) then raise exception 'Not permitted' using errcode='42501';end if;
  select data into d from company_private.versions where item_id=p_id and version=p_version;
  if d is null or (p_action='ack' and (not (d->>'requires_ack')::boolean or not company_private.audience(d))) then raise exception 'Invalid acknowledgement version' using errcode='22023';end if;
  insert into company_private.receipts(item_id,version,user_id,read_at,ack_at) values(p_id,p_version,me,now(),case when p_action='ack' then now() end)
   on conflict(item_id,version,user_id) do update set read_at=coalesce(company_private.receipts.read_at,excluded.read_at),ack_at=coalesce(company_private.receipts.ack_at,excluded.ack_at);
  result:=jsonb_build_object('id',p_id,'version',p_version,'request_id',p_request);
 elsif p_action in ('save','publish','archive','restore') then
  if not company_private.manager() then raise exception 'Management permission required' using errcode='42501';end if;
  select * into x from company_private.items where id=p_id for update;
  if not found then
   if p_action<>'save' or p_revision is distinct from 0 then raise exception 'Record changed; reload' using errcode='40001';end if;
   perform company_private.validate(p_payload);
   insert into company_private.items(id,draft,created_by) values(p_id,p_payload,me) returning * into x;
  else
   if x.revision is distinct from p_revision then raise exception 'Record changed; reload' using errcode='40001';end if;
   if p_action='save' then
    if x.archived then raise exception 'Restore before editing' using errcode='22023';end if;
    perform company_private.validate(p_payload);
    update company_private.items set draft=p_payload,revision=revision+1,updated_at=now() where id=p_id returning * into x;
   elsif p_action='publish' then
    if x.archived then raise exception 'Restore before publishing' using errcode='22023';end if;
    perform company_private.validate(x.draft,true);
    if exists(select 1 from company_private.versions where item_id=p_id and version=x.current_version and data=x.draft) then raise exception 'This draft is already published' using errcode='22023';end if;
    v:=x.current_version+1;
    insert into company_private.versions(item_id,version,data,published_by) values(p_id,v,x.draft,me);
    update company_private.items set current_version=v,revision=revision+1,updated_at=now() where id=p_id returning * into x;
   else
    update company_private.items set archived=(p_action='archive'),revision=revision+1,updated_at=now() where id=p_id returning * into x;
   end if;
  end if;
  result:=jsonb_build_object('id',p_id,'revision',x.revision,'version',x.current_version,'request_id',p_request);
 else raise exception 'Unknown command' using errcode='22023';end if;
 insert into company_private.commands(id,actor,request,response) values(p_request,me,req,result);
 return result;
end $$;
create function public.snacky_company_command_v1(p_request uuid,p_action text,p_id uuid,p_revision integer default 0,p_version integer default null,p_payload jsonb default '{}')
returns jsonb language sql security invoker set search_path='' as $$select company_private.command(p_request,p_action,p_id,p_revision,p_version,p_payload);$$;
create function company_private.notices() returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 if not company_private.staff() then raise exception 'Not permitted' using errcode='42501';end if;
 select jsonb_build_object('attention_count',count(*) filter(where ((v.data->>'notify')::boolean and r.read_at is null) or ((v.data->>'requires_ack')::boolean and r.ack_at is null)),
  'required_count',count(*) filter(where (v.data->>'requires_ack')::boolean and r.ack_at is null)) into result
 from company_private.items i join company_private.versions v on v.item_id=i.id and v.version=i.current_version
 left join company_private.receipts r on r.item_id=i.id and r.version=v.version and r.user_id=auth.uid()
 where not i.archived and company_private.audience(v.data);
 return result;
end $$;
create function public.snacky_company_notices_v1() returns jsonb language sql stable security invoker set search_path='' as $$select company_private.notices();$$;
create function company_private.workspace(p_id uuid,p_filters jsonb)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare manage boolean:=company_private.manager(); s text:=coalesce(p_filters->>'section','start'); q text:=left(coalesce(p_filters->>'q',''),200);
 off integer:=greatest(0,least(100000,coalesce((p_filters->>'offset')::integer,0))); rows jsonb; total bigint;
 rec jsonb; draft jsonb; history jsonb:='[]'; acknowledgements jsonb:='[]'; directory jsonb:='[]'; x company_private.items%rowtype; ver company_private.versions%rowtype; wanted integer;
begin
 if not company_private.staff() or (s='manage' and not manage) then raise exception 'Not permitted' using errcode='42501';end if;
 if s not in ('start','guides','documents','people','updates','manage') then raise exception 'Invalid section' using errcode='22023';end if;
 with candidates as (
  select i.id,i.revision,i.current_version,i.archived,
   coalesce(v.data,i.draft) data,v.published_at,r.read_at,r.ack_at,
   (select t.full_name from public.team_members t where t.id=nullif(coalesce(v.data,i.draft)->>'owner_id','')::uuid) owner_name
  from company_private.items i left join company_private.versions v on v.item_id=i.id and v.version=i.current_version
  left join company_private.receipts r on r.item_id=i.id and r.version=i.current_version and r.user_id=auth.uid()
  where company_private.visible(i.id) and (case when s='manage' then true else not i.archived end)
 ), filtered as (
  select * from candidates c where
   (s='manage' or (s='start' and (data->>'section' in ('start','people') or (data->>'requires_ack')::boolean)) or data->>'section'=s or
    (s='updates' and current_version>0 and company_private.audience(data) and (((data->>'notify')::boolean and read_at is null) or ((data->>'requires_ack')::boolean and ack_at is null))))
   and (q='' or position(lower(q) in lower((data->>'title_en')||' '||(data->>'title_ar')||' '||(data->>'summary_en')||' '||(data->>'summary_ar')||' '||(data->>'body_en')||' '||(data->>'body_ar')))>0)
   and (coalesce(p_filters->>'state','')='' or (p_filters->>'state'='draft' and current_version=0) or (p_filters->>'state'='archived' and archived) or (p_filters->>'state'='review' and not archived and nullif(data->>'review_date','')::date<=(now() at time zone 'Africa/Tripoli')::date))
 ) select (select count(*) from filtered),coalesce((select jsonb_agg(to_jsonb(p)) from (select * from filtered order by published_at desc nulls first,id limit 20 offset off) p),'[]') into total,rows;
 if p_id is not null then
  if not company_private.visible(p_id) then raise exception 'Not permitted' using errcode='42501';end if;
  select * into x from company_private.items where id=p_id;
  if p_filters ? 'version' and (nullif(p_filters->>'version','')::integer is null or (p_filters->>'version')::integer<1) then raise exception 'Invalid published version' using errcode='22023';end if;
  wanted:=coalesce((p_filters->>'version')::integer,x.current_version);
  if wanted=0 and not manage then raise exception 'Draft is private' using errcode='42501';end if;
  if wanted>0 and not company_private.visible(p_id,wanted) then raise exception 'Not permitted' using errcode='42501';end if;
  select * into ver from company_private.versions where item_id=p_id and version=wanted;
  if wanted>0 and ver.item_id is null then raise exception 'Version not found' using errcode='22023';end if;
  rec:=jsonb_build_object('id',x.id,'revision',x.revision,'current_version',wanted,'archived',x.archived,'data',coalesce(ver.data,x.draft),'published_at',ver.published_at,
   'owner_name',(select t.full_name from public.team_members t where t.id=nullif(coalesce(ver.data,x.draft)->>'owner_id','')::uuid),
   'read_at',(select r.read_at from company_private.receipts r where r.item_id=p_id and r.version=wanted and r.user_id=auth.uid()),
   'ack_at',(select r.ack_at from company_private.receipts r where r.item_id=p_id and r.version=wanted and r.user_id=auth.uid()));
  if manage then draft:=x.draft;end if;
  select coalesce(jsonb_agg(jsonb_build_object('version',v.version,'published_at',v.published_at,'title_en',v.data->>'title_en','title_ar',v.data->>'title_ar') order by v.version desc),'[]') into history
   from company_private.versions v where v.item_id=p_id and company_private.visible(p_id,v.version);
  if manage and wanted>0 then
   select coalesce(jsonb_agg(jsonb_build_object('name',t.full_name,'active',p.active_status='active' and t.active_status='active' and t.active is not false,'read_at',r.read_at,'ack_at',r.ack_at) order by t.full_name),'[]') into acknowledgements
   from public.profiles p join public.team_members t on t.id=p.team_member_id
   left join company_private.receipts r on r.item_id=p_id and r.version=wanted and r.user_id=p.id
   where (coalesce(p.roles::text[],'{}')||array[p.role::text]||coalesce(t.roles::text[],'{}')||array[t.role::text]) && array(select jsonb_array_elements_text(ver.data->'audience')) or r.user_id is not null;
  end if;
 end if;
 if manage then select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.full_name) order by t.full_name),'[]') into directory from public.team_members t where t.active_status='active' and t.active is not false;end if;
 return jsonb_build_object('manager',manage,'rows',rows,'total',total,'offset',off,'record',rec,'draft',draft,'history',history,'acknowledgements',acknowledgements,'directory',directory)||company_private.notices();
end $$;
create function public.snacky_company_workspace_v1(p_id uuid default null,p_filters jsonb default '{}') returns jsonb language sql stable security invoker set search_path='' as $$select company_private.workspace(p_id,p_filters);$$;
create function company_private.file(p_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare f company_private.files%rowtype;
begin
 select * into f from company_private.files where id=p_id;
 if f.id is null or not company_private.file_access(f.object_path) then raise exception 'Not permitted' using errcode='42501';end if;
 return jsonb_build_object('id',f.id,'object_path',f.object_path,'original_name',f.original_name,'mime_type',f.mime_type,'digest',f.digest);
end $$;
create function public.snacky_company_file_v1(p_id uuid) returns jsonb language sql stable security invoker set search_path='' as $$select company_private.file(p_id);$$;
-- Narrow function grants; private table access stays denied even to authenticated managers.
revoke all on all functions in schema company_private from public,anon,authenticated;
grant execute on function company_private.file_access(text),company_private.command(uuid,text,uuid,integer,integer,jsonb),company_private.workspace(uuid,jsonb),company_private.notices(),company_private.file(uuid) to authenticated;
revoke all on function public.snacky_company_file_access(text),public.snacky_company_command_v1(uuid,text,uuid,integer,integer,jsonb),public.snacky_company_workspace_v1(uuid,jsonb),public.snacky_company_notices_v1(),public.snacky_company_file_v1(uuid) from public,anon;
grant execute on function public.snacky_company_file_access(text),public.snacky_company_command_v1(uuid,text,uuid,integer,integer,jsonb),public.snacky_company_workspace_v1(uuid,jsonb),public.snacky_company_notices_v1(),public.snacky_company_file_v1(uuid) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('company-documents','company-documents',false,4000000,array['application/pdf','image/jpeg','image/png','image/webp','image/svg+xml','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
create policy company_files_read on storage.objects for select to authenticated using(bucket_id='company-documents' and public.snacky_company_file_access(name));
create policy company_files_insert on storage.objects for insert to authenticated with check(bucket_id='company-documents' and public.snacky_current_profile_has_any_role(array['owner','admin']) and split_part(name,'/',1)=auth.uid()::text);
-- Restrictive policies prevent an older broad storage policy from bypassing this bucket's privacy/immutability.
create policy company_files_read_boundary on storage.objects as restrictive for select to authenticated using(bucket_id<>'company-documents' or public.snacky_company_file_access(name));
create policy company_files_insert_boundary on storage.objects as restrictive for insert to authenticated with check(bucket_id<>'company-documents' or (public.snacky_current_profile_has_any_role(array['owner','admin']) and split_part(name,'/',1)=auth.uid()::text));
create policy company_files_no_update on storage.objects as restrictive for update to authenticated using(bucket_id<>'company-documents') with check(bucket_id<>'company-documents');
create policy company_files_no_delete on storage.objects as restrictive for delete to authenticated using(bucket_id<>'company-documents');
-- Compose the known existing pure-CRM storage boundary, preserving its original scopes.
drop policy crm_storage_boundary on storage.objects;
create policy crm_storage_boundary on storage.objects as restrictive for all to authenticated
 using(not public.snacky_crm_is_limited() or (bucket_id='company-documents' and public.snacky_company_file_access(name)) or (
  bucket_id='crm-documents' and case when split_part(name,'/',3)~'^[0-9a-fA-F-]{36}$' then public.snacky_crm_allowed(split_part(name,'/',2),split_part(name,'/',3)::uuid) else false end))
 with check(not public.snacky_crm_is_limited() or (
  bucket_id='crm-documents' and split_part(name,'/',1)=auth.uid()::text
  and case when split_part(name,'/',3)~'^[0-9a-fA-F-]{36}$' then public.snacky_crm_allowed(split_part(name,'/',2),split_part(name,'/',3)::uuid,true) else false end));
-- Extend only the reviewed read/command allowlist; do not replace or configure another pre-request hook.
create or replace function public.snacky_crm_api_request_guard()
returns void language plpgsql security definer set search_path=public,pg_catalog as $$
declare path text:=coalesce(current_setting('request.path',true),'');method text:=upper(coalesce(current_setting('request.method',true),''));
begin
 if not public.snacky_crm_is_limited() then return;end if;
 if not public.snacky_current_profile_has_any_role(array['crm']) then raise exception 'This account is inactive' using errcode='42501';end if;
 path:=regexp_replace(path,'^/rest/v1','');
 if path in ('/rpc/snacky_crm_workspace_v1','/rpc/snacky_crm_command_v1','/rpc/snacky_crm_timeline_v1','/rpc/snacky_crm_allowed','/rpc/snacky_current_team_member_id','/rpc/snacky_current_profile_has_any_role',
  '/rpc/snacky_company_workspace_v1','/rpc/snacky_company_command_v1','/rpc/snacky_company_notices_v1','/rpc/snacky_company_file_v1','/rpc/snacky_company_file_access') then return;end if;
 if method in ('GET','HEAD') and path in ('/profiles','/team_members','/crm_documents','/investor_agreements','/investor_monthly_statements','/investor_payments','/investor_contributions','/investor_historical_months') then return;end if;
 raise exception 'Use the assigned Customer Relations workspace for this account' using errcode='42501';
end $$;
revoke all on function public.snacky_crm_api_request_guard() from public;
grant execute on function public.snacky_crm_api_request_guard() to authenticated,anon,service_role;
notify pgrst,'reload schema';
