-- Assigned, blind physical storage counts with owner-approved ledger corrections.
-- Generated by Supabase CLI 2.117.0 as assigned_storage_stocktake_v1.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';

create schema if not exists stocktake_private;

create table stocktake_private.assignments (
  id uuid primary key,
  storage_location_id uuid not null references public.storage_locations(id),
  assigned_to uuid not null references public.profiles(id),
  title text not null,
  due_on date,
  notes text,
  status text not null default 'assigned'
    check (status in ('assigned','counting','submitted','needs_recount','approved','cancelled')),
  revision integer not null default 1 check (revision > 0),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  review_note text,
  cancelled_by uuid references public.profiles(id),
  cancelled_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index assigned_storage_stocktake_one_active_location
  on stocktake_private.assignments(storage_location_id)
  where status in ('assigned','counting','submitted','needs_recount');

create table stocktake_private.lines (
  assignment_id uuid not null references stocktake_private.assignments(id) on delete cascade,
  product_id uuid not null references public.products(id),
  product_name text not null,
  sku text,
  category text,
  case_quantity integer not null default 1 check (case_quantity > 0),
  baseline_qty integer not null default 0 check (baseline_qty >= 0),
  added_during_count boolean not null default false,
  counted_qty integer check (counted_qty >= 0),
  counted_at timestamptz,
  counted_by uuid references public.profiles(id),
  expected_at_count integer,
  variance_delta integer,
  adjustment_movement_id uuid references public.inventory_movements(id),
  updated_at timestamptz not null default now(),
  primary key (assignment_id, product_id),
  check ((counted_qty is null and counted_at is null and counted_by is null)
      or (counted_qty is not null and counted_at is not null and counted_by is not null))
);
create index assigned_storage_stocktake_lines_assignment
  on stocktake_private.lines(assignment_id, product_name, product_id);

create table stocktake_private.events (
  id bigint generated always as identity primary key,
  assignment_id uuid not null references stocktake_private.assignments(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid not null references public.profiles(id),
  detail jsonb not null default '{}'::jsonb,
  event_at timestamptz not null default now()
);
create index assigned_storage_stocktake_events_assignment
  on stocktake_private.events(assignment_id,event_at,id);

create table stocktake_private.requests (
  request_id uuid primary key,
  actor_user_id uuid not null references public.profiles(id),
  assignment_id uuid,
  command jsonb not null,
  result jsonb,
  created_at timestamptz not null default now()
);

alter table stocktake_private.assignments enable row level security;
alter table stocktake_private.lines enable row level security;
alter table stocktake_private.events enable row level security;
alter table stocktake_private.requests enable row level security;
revoke all on all tables in schema stocktake_private from public, anon, authenticated;
revoke all on all sequences in schema stocktake_private from public, anon, authenticated;

create or replace function stocktake_private.manager()
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth
as $$
  select auth.uid() is not null
    and public.snacky_current_profile_has_any_role(array['owner','admin']);
$$;

create or replace function stocktake_private.eligible_assignee(p_user uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.team_members tm
      on tm.id=p.team_member_id or tm.auth_user_id=p.id
    where p.id=p_user
      and p.active_status='active'
      and coalesce(tm.active_status='active', case when tm.active is false then false else true end)
      and (
        public.snacky_profile_has_any_role(p.roles,p.role,array['operator','warehouse','purchasing','supervisor'])
        or public.snacky_profile_has_any_role(tm.roles,tm.role,array['operator','warehouse','purchasing','supervisor'])
      )
  );
$$;

create or replace function stocktake_private.ledger_quantity_at(
  p_storage uuid, p_product uuid, p_at timestamptz
)
returns integer language sql stable security definer
set search_path = pg_catalog, public
as $$
  with deltas as (
    select im.quantity::bigint as qty
    from public.inventory_movements im
    where im.product_id=p_product
      and im.to_entity_type::text='storage'
      and im.to_entity_id=p_storage
      and im.created_at <= p_at
    union all
    select -im.quantity::bigint
    from public.inventory_movements im
    where im.product_id=p_product
      and im.from_entity_type::text='storage'
      and im.from_entity_id=p_storage
      and im.created_at <= p_at
  )
  select greatest(coalesce(sum(qty),0),0)::integer from deltas;
$$;

create or replace function stocktake_private.can_view(p_id uuid)
returns boolean language sql stable security definer
set search_path = pg_catalog, public, auth, stocktake_private
as $$
  select stocktake_private.manager()
    or exists(
      select 1 from stocktake_private.assignments a
      where a.id=p_id and a.assigned_to=auth.uid()
    );
$$;

create or replace function stocktake_private.workspace(p_id uuid default null, p_filters jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable security definer
set search_path = pg_catalog, public, auth, stocktake_private
as $$
declare
  v_actor uuid := auth.uid();
  v_manager boolean := stocktake_private.manager();
  v_record jsonb;
  v_rows jsonb;
  v_lines jsonb := '[]'::jsonb;
  v_people jsonb := '[]'::jsonb;
  v_locations jsonb := '[]'::jsonb;
  v_options jsonb := '[]'::jsonb;
begin
  if v_actor is null then
    raise exception 'Sign in required' using errcode='42501';
  end if;

  if p_id is not null and not stocktake_private.can_view(p_id) then
    raise exception 'Stocktake is not assigned to this account' using errcode='42501';
  end if;

  select coalesce(jsonb_agg(row_json order by sort_at desc, id), '[]'::jsonb)
  into v_rows
  from (
    select a.id,
      jsonb_build_object(
        'id',a.id,'title',a.title,'status',a.status,'revision',a.revision,
        'due_on',a.due_on,'storage_location_id',a.storage_location_id,
        'storage_name',sl.name,'assigned_to',a.assigned_to,'assigned_name',p.full_name,
        'created_at',a.created_at,'submitted_at',a.submitted_at,'approved_at',a.approved_at,
        'counted_lines',(select count(*) from stocktake_private.lines l where l.assignment_id=a.id and l.counted_qty is not null),
        'total_lines',(select count(*) from stocktake_private.lines l where l.assignment_id=a.id)
      ) as row_json,
      coalesce(a.updated_at,a.created_at) sort_at
    from stocktake_private.assignments a
    join public.storage_locations sl on sl.id=a.storage_location_id
    join public.profiles p on p.id=a.assigned_to
    where v_manager or a.assigned_to=v_actor
  ) q;

  if p_id is not null then
    select jsonb_build_object(
      'id',a.id,'title',a.title,'notes',a.notes,'status',a.status,'revision',a.revision,
      'due_on',a.due_on,'storage_location_id',a.storage_location_id,'storage_name',sl.name,
      'assigned_to',a.assigned_to,'assigned_name',p.full_name,'created_at',a.created_at,
      'submitted_at',a.submitted_at,'approved_at',a.approved_at,'review_note',case when v_manager then a.review_note else null end
    )
    into v_record
    from stocktake_private.assignments a
    join public.storage_locations sl on sl.id=a.storage_location_id
    join public.profiles p on p.id=a.assigned_to
    where a.id=p_id;

    select coalesce(jsonb_agg(
      case when v_manager then
        jsonb_build_object(
          'product_id',l.product_id,'name',l.product_name,'sku',l.sku,'category',l.category,
          'case_quantity',l.case_quantity,'added_during_count',l.added_during_count,
          'counted_qty',l.counted_qty,'counted_at',l.counted_at,
          'baseline_qty',l.baseline_qty,
          'expected_at_count',case when l.counted_at is null then null else stocktake_private.ledger_quantity_at(a.storage_location_id,l.product_id,l.counted_at) end,
          'current_qty',stocktake_private.ledger_quantity_at(a.storage_location_id,l.product_id,now()),
          'variance_delta',case when l.counted_at is null then null else l.counted_qty-stocktake_private.ledger_quantity_at(a.storage_location_id,l.product_id,l.counted_at) end,
          'adjustment_movement_id',l.adjustment_movement_id
        )
      else
        jsonb_build_object(
          'product_id',l.product_id,'name',l.product_name,'sku',l.sku,'category',l.category,
          'case_quantity',l.case_quantity,'added_during_count',l.added_during_count,
          'counted_qty',l.counted_qty,'counted_at',l.counted_at
        )
      end
      order by l.product_name,l.product_id
    ),'[]'::jsonb)
    into v_lines
    from stocktake_private.lines l
    join stocktake_private.assignments a on a.id=l.assignment_id
    where l.assignment_id=p_id;

    if v_manager then
      select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.full_name) order by p.full_name),'[]'::jsonb)
      into v_people
      from public.profiles p
      where stocktake_private.eligible_assignee(p.id);

      select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'name',s.name) order by s.name),'[]'::jsonb)
      into v_locations
      from public.storage_locations s
      where coalesce(s.active,true)=true
        and s.location_type in ('main_storage','vehicle','temporary','other');
    end if;

    if v_manager or exists(select 1 from stocktake_private.assignments a where a.id=p_id and a.assigned_to=v_actor and a.status in ('assigned','counting','needs_recount')) then
      select coalesce(jsonb_agg(jsonb_build_object(
        'id',p.id,'name',p.name,'sku',p.sku,'category',p.category,
        'case_quantity',greatest(coalesce(p.case_quantity,1),1)
      ) order by p.name),'[]'::jsonb)
      into v_options
      from public.products p
      where p.active=true
        and not exists(select 1 from stocktake_private.lines l where l.assignment_id=p_id and l.product_id=p.id);
    end if;
  elsif v_manager then
    select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.full_name) order by p.full_name),'[]'::jsonb)
    into v_people from public.profiles p where stocktake_private.eligible_assignee(p.id);
    select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'name',s.name) order by s.name),'[]'::jsonb)
    into v_locations from public.storage_locations s
    where coalesce(s.active,true)=true and s.location_type in ('main_storage','vehicle','temporary','other');
  end if;

  return jsonb_build_object(
    'manager',v_manager,'today',(now() at time zone 'Africa/Tripoli')::date,
    'rows',v_rows,'record',v_record,'lines',v_lines,'people',v_people,'locations',v_locations,'options',v_options
  );
end;
$$;

create or replace function stocktake_private.command(p_command jsonb)
returns jsonb language plpgsql security definer
set search_path = pg_catalog, public, auth, stocktake_private
as $$
declare
  v_actor uuid := auth.uid();
  v_request uuid;
  v_id uuid;
  v_action text;
  v_revision integer;
  v_payload jsonb;
  v_existing stocktake_private.requests%rowtype;
  v_assignment stocktake_private.assignments%rowtype;
  v_result jsonb;
  v_item jsonb;
  v_product uuid;
  v_count integer;
  v_now timestamptz := now();
  v_expected integer;
  v_delta integer;
  v_movement uuid;
  v_submission uuid;
begin
  if v_actor is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if jsonb_typeof(p_command) <> 'object' then raise exception 'Invalid command' using errcode='22023'; end if;

  begin
    v_request := (p_command->>'request_id')::uuid;
    v_id := (p_command->>'assignment_id')::uuid;
    v_revision := coalesce((p_command->>'revision')::integer,0);
  exception when others then
    raise exception 'Invalid command identity' using errcode='22023';
  end;
  v_action := lower(trim(coalesce(p_command->>'action','')));
  v_payload := coalesce(p_command->'payload','{}'::jsonb);
  if v_request is null or v_id is null or v_action not in ('create','save','add_product','submit','recount','approve','cancel') then
    raise exception 'Invalid stocktake command' using errcode='22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('snacky:stocktake:'||v_request::text,0));
  select * into v_existing from stocktake_private.requests where request_id=v_request for update;
  if found then
    if v_existing.actor_user_id is distinct from v_actor or v_existing.command is distinct from p_command then
      raise exception 'Request id was already used for another stocktake command' using errcode='23505';
    end if;
    if v_existing.result is not null then return v_existing.result; end if;
  else
    insert into stocktake_private.requests(request_id,actor_user_id,assignment_id,command)
    values(v_request,v_actor,v_id,p_command);
  end if;

  if v_action='create' then
    if not stocktake_private.manager() then raise exception 'Owner or admin required' using errcode='42501'; end if;
    if v_revision <> 0 then raise exception 'New stocktake revision must be zero' using errcode='40001'; end if;
    if not stocktake_private.eligible_assignee((v_payload->>'assigned_to')::uuid) then
      raise exception 'Choose an active warehouse, purchasing, operator, or supervisor account' using errcode='23514';
    end if;
    perform 1 from public.storage_locations s
      where s.id=(v_payload->>'storage_location_id')::uuid and coalesce(s.active,true)=true
        and s.location_type in ('main_storage','vehicle','temporary','other');
    if not found then raise exception 'Active storage location required' using errcode='23503'; end if;
    if nullif(trim(coalesce(v_payload->>'title','')),'') is null then raise exception 'Title required' using errcode='22023'; end if;

    insert into stocktake_private.assignments(
      id,storage_location_id,assigned_to,title,due_on,notes,created_by
    ) values (
      v_id,(v_payload->>'storage_location_id')::uuid,(v_payload->>'assigned_to')::uuid,
      trim(v_payload->>'title'),nullif(v_payload->>'due_on','')::date,
      nullif(trim(coalesce(v_payload->>'notes','')),''),v_actor
    );

    insert into stocktake_private.lines(
      assignment_id,product_id,product_name,sku,category,case_quantity,baseline_qty
    )
    select v_id,p.id,p.name,p.sku,p.category,greatest(coalesce(p.case_quantity,1),1),
      greatest(coalesce(i.quantity_on_hand,0),0)
    from public.products p
    join public.current_inventory_by_location i
      on i.product_id=p.id and i.location_type='storage'
      and i.location_id=(v_payload->>'storage_location_id')::uuid
    where p.active=true and i.quantity_on_hand > 0;

    insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
    values(v_id,'created',v_actor,jsonb_build_object('assigned_to',v_payload->>'assigned_to','storage_location_id',v_payload->>'storage_location_id'));
    v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',1);

  else
    select * into v_assignment from stocktake_private.assignments where id=v_id for update;
    if not found then raise exception 'Stocktake not found' using errcode='P0002'; end if;

    if v_action in ('save','add_product','submit') then
      if v_assignment.assigned_to is distinct from v_actor then raise exception 'Stocktake is not assigned to this account' using errcode='42501'; end if;
      if v_assignment.status not in ('assigned','counting','needs_recount') then raise exception 'Stocktake is not open for counting' using errcode='23514'; end if;
      if v_revision <> v_assignment.revision then raise exception 'Stocktake changed; reload before saving' using errcode='40001'; end if;
    else
      if not stocktake_private.manager() then raise exception 'Owner or admin required' using errcode='42501'; end if;
      if v_revision <> v_assignment.revision then raise exception 'Stocktake changed; reload before review' using errcode='40001'; end if;
    end if;

    if v_action='save' then
      if jsonb_typeof(v_payload->'counts') <> 'array' or jsonb_array_length(v_payload->'counts')=0 then
        raise exception 'At least one count is required' using errcode='22023';
      end if;
      for v_item in select value from jsonb_array_elements(v_payload->'counts')
      loop
        begin
          v_product:=(v_item->>'product_id')::uuid; v_count:=(v_item->>'counted_qty')::integer;
        exception when others then raise exception 'Invalid count line' using errcode='22023'; end;
        if v_count < 0 then raise exception 'Count cannot be negative' using errcode='23514'; end if;
        update stocktake_private.lines
        set counted_qty=v_count,counted_at=v_now,counted_by=v_actor,updated_at=v_now
        where assignment_id=v_id and product_id=v_product;
        if not found then raise exception 'Counted product is not on this stocktake' using errcode='23503'; end if;
      end loop;
      update stocktake_private.assignments set status='counting',revision=revision+1,updated_at=v_now where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'counts_saved',v_actor,jsonb_build_object('lines',jsonb_array_length(v_payload->'counts')));
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);

    elsif v_action='add_product' then
      begin v_product:=(v_payload->>'product_id')::uuid; exception when others then raise exception 'Valid product required' using errcode='22023'; end;
      insert into stocktake_private.lines(
        assignment_id,product_id,product_name,sku,category,case_quantity,baseline_qty,added_during_count
      )
      select v_id,p.id,p.name,p.sku,p.category,greatest(coalesce(p.case_quantity,1),1),
        stocktake_private.ledger_quantity_at(v_assignment.storage_location_id,p.id,v_now),true
      from public.products p where p.id=v_product and p.active=true
      on conflict (assignment_id,product_id) do nothing;
      if not found then raise exception 'Product is already listed or inactive' using errcode='23505'; end if;
      update stocktake_private.assignments set status='counting',revision=revision+1,updated_at=v_now where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'product_added',v_actor,jsonb_build_object('product_id',v_product));
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);

    elsif v_action='submit' then
      if exists(select 1 from stocktake_private.lines where assignment_id=v_id and counted_qty is null) then
        raise exception 'Count every listed product before submitting' using errcode='23514';
      end if;
      if not exists(select 1 from stocktake_private.lines where assignment_id=v_id)
         and coalesce((v_payload->>'confirmed_empty')::boolean,false) is not true then
        raise exception 'Confirm that this storage is physically empty' using errcode='23514';
      end if;
      update stocktake_private.assignments
      set status='submitted',submitted_at=v_now,revision=revision+1,updated_at=v_now
      where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'submitted',v_actor,'{}');
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);

    elsif v_action='recount' then
      if v_assignment.status <> 'submitted' then raise exception 'Only a submitted stocktake can be sent back' using errcode='23514'; end if;
      update stocktake_private.lines set counted_qty=null,counted_at=null,counted_by=null,expected_at_count=null,variance_delta=null,adjustment_movement_id=null,updated_at=v_now where assignment_id=v_id;
      update stocktake_private.assignments
      set status='needs_recount',submitted_at=null,review_note=nullif(trim(coalesce(v_payload->>'note','')),''),revision=revision+1,updated_at=v_now
      where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'recount_requested',v_actor,jsonb_build_object('note',v_payload->>'note'));
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);

    elsif v_action='approve' then
      if v_assignment.status <> 'submitted' then raise exception 'Only a submitted stocktake can be approved' using errcode='23514'; end if;
      if exists(select 1 from stocktake_private.lines where assignment_id=v_id and (counted_qty is null or counted_at is null)) then
        raise exception 'Stocktake has incomplete counts' using errcode='23514';
      end if;

      for v_item in
        select jsonb_build_object('product_id',l.product_id,'counted_qty',l.counted_qty,'counted_at',l.counted_at)
        from stocktake_private.lines l where l.assignment_id=v_id order by l.product_id
      loop
        v_product:=(v_item->>'product_id')::uuid;
        v_count:=(v_item->>'counted_qty')::integer;
        v_expected:=stocktake_private.ledger_quantity_at(v_assignment.storage_location_id,v_product,(v_item->>'counted_at')::timestamptz);
        v_delta:=v_count-v_expected;
        v_movement:=null;
        if v_delta <> 0 then
          v_submission := (md5(v_request::text||':'||v_product::text))::uuid;
          select movement_id into v_movement
          from public.snacky_create_storage_adjustment_v1(
            v_submission::text,v_product,v_assignment.storage_location_id,
            case when v_delta>0 then 'add' else 'remove' end,
            abs(v_delta),'stock_count_correction',
            'Approved assigned stocktake '||v_id::text||' · counted '||v_count::text||
              ' · ledger at count '||v_expected::text||' · variance '||case when v_delta>0 then '+' else '' end||v_delta::text,
            null
          );
        end if;
        update stocktake_private.lines
        set expected_at_count=v_expected,variance_delta=v_delta,adjustment_movement_id=v_movement,updated_at=v_now
        where assignment_id=v_id and product_id=v_product;
      end loop;
      update stocktake_private.assignments
      set status='approved',approved_by=v_actor,approved_at=v_now,review_note=nullif(trim(coalesce(v_payload->>'note','')),''),
          revision=revision+1,updated_at=v_now
      where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'approved',v_actor,jsonb_build_object('review_note',v_payload->>'note'));
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);

    else
      if v_assignment.status='approved' then raise exception 'Approved stocktakes cannot be cancelled' using errcode='23514'; end if;
      update stocktake_private.assignments
      set status='cancelled',cancelled_by=v_actor,cancelled_at=v_now,review_note=nullif(trim(coalesce(v_payload->>'note','')),''),
          revision=revision+1,updated_at=v_now
      where id=v_id returning revision into v_revision;
      insert into stocktake_private.events(assignment_id,event_type,actor_user_id,detail)
      values(v_id,'cancelled',v_actor,jsonb_build_object('note',v_payload->>'note'));
      v_result:=jsonb_build_object('ok',true,'request_id',v_request,'assignment_id',v_id,'action',v_action,'revision',v_revision);
    end if;
  end if;

  update stocktake_private.requests set result=v_result where request_id=v_request;
  return v_result;
end;
$$;

revoke all on function stocktake_private.manager() from public,anon,authenticated;
revoke all on function stocktake_private.eligible_assignee(uuid) from public,anon,authenticated;
revoke all on function stocktake_private.ledger_quantity_at(uuid,uuid,timestamptz) from public,anon,authenticated;
revoke all on function stocktake_private.can_view(uuid) from public,anon,authenticated;
revoke all on function stocktake_private.workspace(uuid,jsonb) from public,anon,authenticated;
revoke all on function stocktake_private.command(jsonb) from public,anon,authenticated;

grant usage on schema stocktake_private to authenticated;
grant execute on function stocktake_private.workspace(uuid,jsonb) to authenticated;
grant execute on function stocktake_private.command(jsonb) to authenticated;

create or replace function public.snacky_storage_stocktake_workspace_v1(p_id uuid default null,p_filters jsonb default '{}'::jsonb)
returns jsonb language sql security invoker
set search_path = pg_catalog, stocktake_private
as $$ select stocktake_private.workspace(p_id,p_filters); $$;

create or replace function public.snacky_storage_stocktake_command_v1(p_command jsonb)
returns jsonb language sql security invoker
set search_path = pg_catalog, stocktake_private
as $$ select stocktake_private.command(p_command); $$;

revoke all on function public.snacky_storage_stocktake_workspace_v1(uuid,jsonb) from public,anon;
revoke all on function public.snacky_storage_stocktake_command_v1(jsonb) from public,anon;
grant execute on function public.snacky_storage_stocktake_workspace_v1(uuid,jsonb) to authenticated;
grant execute on function public.snacky_storage_stocktake_command_v1(jsonb) to authenticated;

select pg_notify('pgrst','reload schema');
commit;
